import type { BuilderState, BuilderTable, GenFile } from './builder';
import { toClassName } from './builder';
import { canonicalType, sortTablesTopologically } from '@/database/schemaAst';
import { getCanonicalAuthRoutes } from '@/security/authContract';

function header(comment: string, namespace?: string): string {
  let s = '<?php\n/**\n * ' + comment + '\n * Generated by PHP Backend Builder - PHP 8.2 + PDO + MySQL\n * All queries use prepared statements. No framework required.\n */\n\ndeclare(strict_types=1);\n\n';
  if (namespace) {
    s += 'namespace ' + namespace + ';\n\n';
  }
  return s;
}

function nljoin(lines: string[]): string {
  // SQL definitions MUST be comma-separated — join with ",\n" to guarantee
  // syntactically valid output (regression: missing commas produced invalid SQL).
  return lines.join(',\n');
}

// Single source of truth for SQL types: route through canonicalType (IR/AST)
// so TEXT fields (message/body/content/...) can NEVER become INT in any artifact.
function sqlTypeForCanonical(colName: string, rawType: string): string {
  const mapped = canonicalType(colName, rawType);
  switch (mapped.t) {
    case 'BIGINT': return 'BIGINT';
    case 'SMALLINT': return 'SMALLINT';
    case 'TINYINT': return 'TINYINT(1)';
    case 'INT': return 'INT';
    case 'DECIMAL': return 'DECIMAL(10,2)';
    case 'FLOAT': return 'FLOAT';
    case 'DOUBLE': return 'DOUBLE';
    case 'VARCHAR': return `VARCHAR(${mapped.len ?? 255})`;
    case 'TEXT': return 'TEXT';
    case 'LONGTEXT': return 'LONGTEXT';
    case 'DATETIME': return 'DATETIME';
    case 'TIMESTAMP': return 'TIMESTAMP';
    case 'DATE': return 'DATE';
    case 'TIME': return 'TIME';
    case 'YEAR': return 'YEAR';
    case 'JSON': return 'JSON';
    case 'BLOB': return 'LONGBLOB';
    case 'BOOLEAN': return 'TINYINT(1)';
    case 'CHAR': return `CHAR(${mapped.len ?? 36})`;
    default: return 'VARCHAR(255)';
  }
}

function dbColumnsSql(t: BuilderTable): string[] {
  const lines: string[] = [];
  for (const c of t.columns) {
    let def = '  ' + c.name + ' ' + sqlTypeForCanonical(c.name, c.type);
    if (c.isAutoIncrement) def += ' AUTO_INCREMENT';
    def += c.nullable ? ' NULL' : ' NOT NULL';
    if (c.unique && !c.isPrimaryKey) def += ' UNIQUE';
    if (c.defaultValue !== '') {
      const needsQuote = ['varchar', 'text', 'longtext', 'datetime', 'timestamp', 'date', 'time', 'enum', 'set', 'uuid'].includes(c.type);
      const safe = c.defaultValue.split("'").join("\\'");
      def += needsQuote ? " DEFAULT '" + safe + "'" : ' DEFAULT ' + c.defaultValue;
    }
    lines.push(def);
  }
  const pk = t.columns.filter((c) => c.isPrimaryKey).map((c) => c.name);
  if (pk.length) lines.push('  PRIMARY KEY (' + pk.join(', ') + ')');
  if (t.timestamps && !t.columns.some((c) => c.name === 'created_at')) {
    lines.push('  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP');
  }
  if (t.timestamps && !t.columns.some((c) => c.name === 'updated_at')) {
    lines.push('  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP');
  }
  if (t.softDeletes && !t.columns.some((c) => c.name === 'deleted_at')) {
    lines.push('  deleted_at TIMESTAMP NULL DEFAULT NULL');
  }
  for (const c of t.columns) {
    if (c.foreignKey) {
      lines.push('  CONSTRAINT fk_' + t.name + '_' + c.name + ' FOREIGN KEY (' + c.name + ') REFERENCES ' + c.foreignKey.table + ' (' + c.foreignKey.column + ') ON DELETE CASCADE ON UPDATE CASCADE');
    }
  }
  return lines;
}

function migrationFor(t: BuilderTable): string {
  const cols = nljoin(dbColumnsSql(t));
  return header('Migration: create table ' + t.name) +
    'return new class {\n' +
    '    public function up(PDO $pdo): void\n' +
    '    {\n' +
    '        $pdo->exec("CREATE TABLE IF NOT EXISTS ' + t.name + ' (\n' + cols + '\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");\n' +
    '    }\n\n' +
    '    public function down(PDO $pdo): void\n' +
    '    {\n' +
    '        $pdo->exec("DROP TABLE IF EXISTS ' + t.name + '");\n' +
    '    }\n' +
    '};\n';
}

/**
 * Type-consistency guarantee: model casts derive from the SAME canonical type
 * as SQL generation. message=TEXT → model string, OpenAPI string, client string.
 * Exported for validation pipeline consistency checks.
 */
export function canonicalCastFor(colName: string, rawType: string): string | null {
  const mapped = canonicalType(colName, rawType);
  if (['INT', 'BIGINT', 'SMALLINT', 'TINYINT'].includes(mapped.t)) return 'int';
  if (['DECIMAL', 'FLOAT', 'DOUBLE'].includes(mapped.t)) return 'float';
  if (mapped.t === 'BOOLEAN' || mapped.t === 'TINYINT') {
    // boolean storage is TINYINT(1); only true boolean semantic → bool
    return rawType === 'boolean' ? 'bool' : 'int';
  }
  if (mapped.t === 'JSON') return 'array';
  return null; // strings need no cast
}

export function openApiTypeFor(colName: string, rawType: string): { type: string; format?: string } {
  const mapped = canonicalType(colName, rawType);
  if (['INT', 'BIGINT', 'SMALLINT', 'TINYINT'].includes(mapped.t)) return { type: 'integer', format: mapped.t.toLowerCase() };
  if (['DECIMAL', 'FLOAT', 'DOUBLE'].includes(mapped.t)) return { type: 'number' };
  if (mapped.t === 'BOOLEAN') return { type: 'boolean' };
  if (['DATETIME', 'TIMESTAMP', 'DATE', 'TIME', 'YEAR'].includes(mapped.t)) return { type: 'string', format: 'date-time' };
  if (mapped.t === 'JSON') return { type: 'object' };
  if (mapped.t === 'CHAR' && colName === 'id') return { type: 'string', format: 'uuid' };
  return { type: 'string' };
}

function modelFor(t: BuilderTable): string {
  const cls = toClassName(t.name);
  const fillable = t.columns
    .filter((c) => !c.isAutoIncrement && c.name !== 'created_at' && c.name !== 'updated_at' && c.name !== 'deleted_at')
    .map((c) => "        '" + c.name + "'")
    .join(',\n');
  const casts: string[] = [];
  for (const c of t.columns) {
    const cast = canonicalCastFor(c.name, c.type);
    if (cast) casts.push("            '" + c.name + "' => '" + cast + "',");
  }
  const hasSoft = t.softDeletes ? 'true' : 'false';
  const hasPassword = t.columns.some((c) => c.name === 'password');
  const hiddenLine = hasPassword ? "\n    protected static array $hidden = [\n        'password',\n    ];\n" : '';
  return header('Model: ' + cls + ' — fillable/hidden/casts from canonical IR', 'App\\Models') +
    "use App\\Support\\Model;\n\n" +
    'final class ' + cls + ' extends Model\n{\n' +
    "    protected static string $table = '" + t.name + "';\n" +
    '    protected static bool $softDeletes = ' + hasSoft + ';\n' + hiddenLine + '\n' +
    '    protected static array $fillable = [\n' + fillable + '\n    ];\n\n' +
    '    protected static array $casts = [\n' + casts.join('\n') + '\n    ];\n' +
    '}\n';
}

function validationRulesFor(t: BuilderTable): string {
  // Generate per-field rules from IR-canonical types. PATCH passes $isCreate=false
  // so required is skipped on partial updates.
  const lines: string[] = [];
  for (const c of t.columns) {
    if (c.isAutoIncrement || ['created_at', 'updated_at', 'deleted_at', 'id'].includes(c.name)) continue;
    const rules: string[] = [];
    const mapped = canonicalType(c.name, c.type);
    if (!c.nullable) rules.push('required');
    else rules.push('nullable');
    if (['VARCHAR', 'TEXT', 'LONGTEXT', 'CHAR'].includes(mapped.t)) rules.push('string');
    if (['INT', 'BIGINT', 'SMALLINT', 'TINYINT'].includes(mapped.t)) rules.push('integer');
    if (['DECIMAL', 'FLOAT', 'DOUBLE'].includes(mapped.t)) rules.push('numeric');
    if (c.name === 'email') rules.push('email');
    if (/url|website|link/.test(c.name)) rules.push('url');
    if (c.name === 'password') rules.push('min:8');
    if (c.unique) rules.push('unique');
    if (c.foreignKey) rules.push('exists:' + c.foreignKey.table + ',' + c.foreignKey.column);
    if (['DATETIME', 'TIMESTAMP', 'DATE'].includes(mapped.t)) rules.push('date');
    lines.push("        $rules['" + c.name + "'] = '" + rules.join('|') + "';");
  }
  return lines.join('\n');
}

function controllerFor(t: BuilderTable, perPage: number, isAuthResource = false): string {
  const cls = toClassName(t.name);
  const ctrl = cls + 'Controller';
  const required = t.columns
    .filter((c) => !c.nullable && !c.isAutoIncrement && !['created_at', 'updated_at', 'deleted_at'].includes(c.name))
    .map((c) => c.name);
  const reqLines = required.map((r) => "        if ($isCreate && (!isset($data['" + r + "']) || $data['" + r + "'] === '')) { $errors['" + r + "'] = 'The " + r + " field is required.'; }").join('\n');
  const rulesBlock = validationRulesFor(t);
  // Auth-specific behavior ONLY on User/Auth resources (regression: password logic
  // must never leak into ContactController etc.)
  const mutateBody = isAuthResource
    ? "        if (isset($data['password']) && $data['password'] !== '') {\n            $data['password'] = password_hash((string)$data['password'], PASSWORD_BCRYPT);\n        } else { unset($data['password']); }\n        if (isset($data['email'])) { $data['email'] = strtolower(trim((string)$data['email'])); }\n        return $data;"
    : "        if (isset($data['email'])) { $data['email'] = strtolower(trim((string)$data['email'])); }\n        return $data;";
  const sortCols = Array.from(new Set(['id', 'created_at', 'updated_at', ...t.columns.map((c) => c.name).filter((n) => !['password', 'key_hash'].includes(n))]));
  const allowedSortsStr = "['" + sortCols.join("', '") + "']";
  const ownerCol = t.columns.find((c) => ['user_id', 'owner_id', 'created_by', 'author_id'].includes(c.name))?.name;
  const ownerCheck = ownerCol && !isAuthResource
    ? "        if (isset($existing['" + ownerCol + "']) && isset($req->user['sub']) && (string)$existing['" + ownerCol + "'] !== (string)$req->user['sub'] && ($req->user['role'] ?? '') !== 'admin') {\n            Response::error('FORBIDDEN', 'Access denied: you do not own this resource', 403);\n            return;\n        }\n"
    : "";
  const ownerCreate = ownerCol && !isAuthResource
    ? "        if (isset($req->user['sub']) && !isset($data['" + ownerCol + "'])) { $data['" + ownerCol + "'] = $req->user['sub']; }\n"
    : "";

  return header('Controller: ' + ctrl + ' (CRUD + pagination + search + sort + authorization)', 'App\\Controllers') +
    "use App\\Models\\" + cls + ";\n" +
    "use App\\Support\\Request;\n" +
    "use App\\Support\\Response;\n\n" +
    'final class ' + ctrl + '\n{\n' +
    '    public function list(Request $req): void\n' +
    '    {\n' +
    '        $page = max(1, (int)$req->query(' + "'page', '1'" + '));\n' +
    '        $perPage = min(100, max(1, (int)$req->query(' + "'per_page', '" + perPage + "'" + ')));\n' +
    '        $search = trim((string)$req->query(' + "'search', ''" + '));\n' +
    '        $allowedSorts = ' + allowedSortsStr + ';\n' +
    "        $sortParam = (string)$req->query('sort', 'id');\n" +
    "        $sort = in_array($sortParam, $allowedSorts, true) ? $sortParam : 'id';\n" +
    '        $dir = strtoupper((string)$req->query(' + "'dir', 'DESC'" + ")) === 'ASC' ? 'ASC' : 'DESC';\n" +
    '        $result = ' + cls + '::paginate($page, $perPage, $search, $sort, $dir);\n' +
    '        Response::json($result);\n' +
    '    }\n\n' +
    '    public function read(Request $req, string $id): void\n' +
    '    {\n' +
    '        $row = ' + cls + '::find($id);\n' +
    "        if (!$row) { Response::error('NOT_FOUND', 'Not found', 404); return; }\n" +
    "        Response::ok($row);\n" +
    '    }\n\n' +
    '    public function create(Request $req): void\n' +
    '    {\n' +
    '        $data = $req->body();\n' +
    '        $errors = $this->validate($data, true);\n' +
    "        if ($errors) { Response::error('VALIDATION_ERROR', 'Validation failed', 422, $errors); return; }\n" +
    ownerCreate +
    '        $data = $this->mutate($data);\n' +
    '        $row = ' + cls + '::create($data);\n' +
    "        Response::json(['success' => true, 'data' => $row, 'request_id' => $GLOBALS['__request_id'] ?? ''], 201);\n" +
    '    }\n\n' +
    '    public function update(Request $req, string $id): void\n' +
    '    {\n' +
    '        $existing = ' + cls + '::find($id);\n' +
    "        if (!$existing) { Response::error('NOT_FOUND', 'Not found', 404); return; }\n" +
    ownerCheck +
    '        $data = $req->body();\n' +
    '        $errors = $this->validate($data, false);\n' +
    "        if ($errors) { Response::error('VALIDATION_ERROR', 'Validation failed', 422, $errors); return; }\n" +
    '        $data = $this->mutate($data);\n' +
    '        $row = ' + cls + '::update($id, $data);\n' +
    "        Response::ok($row);\n" +
    '    }\n\n' +
    '    public function delete(Request $req, string $id): void\n' +
    '    {\n' +
    '        $existing = ' + cls + '::find($id);\n' +
    "        if (!$existing) { Response::error('NOT_FOUND', 'Not found', 404); return; }\n" +
    ownerCheck +
    '        ' + cls + '::delete($id);\n' +
    "        Response::ok(['deleted' => true]);\n" +
    '    }\n\n' +
    '    public function patch(Request $req, string $id): void\n' +
    '    {\n' +
    '        $existing = ' + cls + '::find($id);\n' +
    "        if (!$existing) { Response::error('NOT_FOUND', 'Not found', 404); return; }\n" +
    ownerCheck +
    '        $data = $req->body();\n' +
    "        if (empty($data)) { Response::error('VALIDATION_ERROR', 'No fields provided for update', 422); return; }\n" +
    '        $errors = $this->validate($data, false);\n' +
    "        if ($errors) { Response::error('VALIDATION_ERROR', 'Validation failed', 422, $errors); return; }\n" +
    '        $data = $this->mutate($data);\n' +
    '        $row = ' + cls + '::update($id, $data);\n' +
    "        Response::ok($row);\n" +
    '    }\n\n' +
    '    /** Validation rules derived from IR (single source of truth). */\n' +
    '    public function rules(): array\n' +
    '    {\n' +
    '        $rules = [];\n' +
    rulesBlock + '\n' +
    '        return $rules;\n' +
    '    }\n\n' +
    '    private function validate(array $data, bool $isCreate): array\n' +
    '    {\n' +
    '        $errors = [];\n' +
    reqLines + '\n' +
    "        if (isset($data['email']) && $data['email'] !== '' && strpos((string)$data['email'], '@') === false) { $errors['email'] = 'Must be a valid email.'; }\n" +
    '        return $errors;\n' +
    '    }\n\n' +
    '    private function mutate(array $data): array\n' +
    '    {\n' +
    mutateBody + '\n' +
    '    }\n' +
    '}\n';
}

const SUPPORT_CONTAINER_LINES: string[] = [
  '<?php',
  '/**',
  ' * PSR-11 compliant Dependency Injection Container.',
  ' * Generated by PHP Backend Builder.',
  ' */',
  '',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'use Closure;',
  'use Exception;',
  'use ReflectionClass;',
  'use ReflectionParameter;',
  '',
  'final class Container',
  '{',
  '    private static ?Container $instance = null;',
  '    private array $bindings = [];',
  '    private array $instances = [];',
  '',
  '    public static function getInstance(): Container',
  '    {',
  '        if (self::$instance === null) {',
  '            self::$instance = new self();',
  '        }',
  '        return self::$instance;',
  '    }',
  '',
  '    public static function setInstance(?Container $container): void',
  '    {',
  '        self::$instance = $container;',
  '    }',
  '',
  '    public function bind(string $abstract, $concrete = null, bool $shared = false): void',
  '    {',
  '        if ($concrete === null) {',
  '            $concrete = $abstract;',
  '        }',
  '        $this->bindings[$abstract] = [',
  "            'concrete' => $concrete,",
  "            'shared' => $shared,",
  '        ];',
  '    }',
  '',
  '    public function singleton(string $abstract, $concrete = null): void',
  '    {',
  '        $this->bind($abstract, $concrete, true);',
  '    }',
  '',
  '    public function instance(string $abstract, $instance): void',
  '    {',
  '        $this->instances[$abstract] = $instance;',
  '    }',
  '',
  '    public function get(string $id)',
  '    {',
  '        if (isset($this->instances[$id])) {',
  '            return $this->instances[$id];',
  '        }',
  '        if (!isset($this->bindings[$id])) {',
  '            if (class_exists($id)) {',
  '                return $this->build($id);',
  '            }',
  '            throw new Exception("Target class or binding [{$id}] does not exist.");',
  '        }',
  "        $concrete = $this->bindings[$id]['concrete'];",
  "        $isShared = $this->bindings[$id]['shared'];",
  '        $object = $this->build($concrete);',
  '        if ($isShared) {',
  '            $this->instances[$id] = $object;',
  '        }',
  '        return $object;',
  '    }',
  '',
  '    public function has(string $id): bool',
  '    {',
  '        return isset($this->bindings[$id]) || isset($this->instances[$id]) || class_exists($id);',
  '    }',
  '',
  '    private function build($concrete)',
  '    {',
  '        if ($concrete instanceof Closure) {',
  '            return $concrete($this);',
  '        }',
  '        if (is_object($concrete)) {',
  '            return $concrete;',
  '        }',
  '        $reflector = new ReflectionClass($concrete);',
  '        if (!$reflector->isInstantiable()) {',
  '            throw new Exception("Target [{$concrete}] is not instantiable.");',
  '        }',
  '        $constructor = $reflector->getConstructor();',
  '        if ($constructor === null) {',
  '            return new $concrete();',
  '        }',
  '        $dependencies = [];',
  '        foreach ($constructor->getParameters() as $parameter) {',
  '            $dependencies[] = $this->resolveDependency($parameter);',
  '        }',
  '        return $reflector->newInstanceArgs($dependencies);',
  '    }',
  '',
  '    private function resolveDependency(ReflectionParameter $param)',
  '    {',
  '        $type = $param->getType();',
  '        if ($type && !$type->isBuiltin()) {',
  '            return $this->get($type->getName());',
  '        }',
  '        if ($param->isDefaultValueAvailable()) {',
  '            return $param->getDefaultValue();',
  '        }',
  '        throw new Exception("Cannot resolve parameter [{$param->getName()}] in class [{$param->getDeclaringClass()->getName()}].");',
  '    }',
  '}',
];

const SUPPORT_MODEL_LINES: string[] = [
  '<?php',
  '/**',
  ' * Base Model - PDO CRUD with prepared statements, pagination, search.',
  ' * Generated by PHP Backend Builder.',
  ' */',
  '',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'use PDO;',
  '',
  'abstract class Model',
  '{',
  "    protected static string $table = '';",
  '    protected static bool $softDeletes = false;',
  '    protected static array $fillable = [];',
  '    protected static array $casts = [];',
  '',
  '    protected static function pdo(): PDO',
  '    {',
  '        $c = Container::getInstance();',
  "        if ($c->has(PDO::class)) {",
  '            return $c->get(PDO::class);',
  '        }',
  '        return db();',
  '    }',
  '',
  '    protected static function filter(array $data): array',
  '    {',
  '        $out = [];',
  '        foreach (static::$fillable as $f) {',
  '            if (array_key_exists($f, $data)) { $out[$f] = $data[$f]; }',
  '        }',
  '        return $out;',
  '    }',
  '',
  '    protected static function castRow(array $row): array',
  '    {',
  '        foreach (static::$casts as $k => $t) {',
  '            if (!array_key_exists($k, $row) || $row[$k] === null) continue;',
  "            if ($t === 'int') $row[$k] = (int)$row[$k];",
  "            elseif ($t === 'float') $row[$k] = (float)$row[$k];",
  "            elseif ($t === 'bool') $row[$k] = (bool)$row[$k];",
  "            elseif ($t === 'array' && is_string($row[$k])) {",
  '                $d = json_decode($row[$k], true);',
  '                $row[$k] = is_array($d) ? $d : [];',
  '            }',
  '        }',
  "        if (isset($row['password'])) unset($row['password']);",
  '        return $row;',
  '    }',
  '',
  '    public static function find(string $id): ?array',
  '    {',
  "        $sql = 'SELECT * FROM ' . static::$table . ' WHERE id = :id';",
  "        if (static::$softDeletes) $sql .= ' AND deleted_at IS NULL';",
  "        $st = static::pdo()->prepare($sql . ' LIMIT 1');",
  "        $st->execute([':id' => $id]);",
  '        $row = $st->fetch(PDO::FETCH_ASSOC);',
  '        return $row ? static::castRow($row) : null;',
  '    }',
  '',
  '    public static function paginate(int $page, int $perPage, string $search, string $sort, string $dir): array',
  '    {',
  '        $offset = ($page - 1) * $perPage;',
  "        $where = '';",
  '        $params = [];',
  "        if (static::$softDeletes) $where = 'WHERE deleted_at IS NULL';",
  "        if ($search !== '') {",
  '            $cols = static::searchable();',
  '            if ($cols) {',
  "                $likes = array_map(fn($c) => $c . ' LIKE :search', $cols);",
  "                $where .= ($where ? ' AND ' : 'WHERE ') . '(' . implode(' OR ', $likes) . ')';",
  "                $params[':search'] = '%' . $search . '%';",
  '            }',
  '        }',
  "        $count = static::pdo()->prepare('SELECT COUNT(*) FROM ' . static::$table . ' ' . $where);",
  '        $count->execute($params);',
  '        $total = (int)$count->fetchColumn();',
  "        $safeDir = strtoupper($dir) === 'ASC' ? 'ASC' : 'DESC';",
  "        $allowedSorts = array_merge(['id', 'created_at', 'updated_at'], static::$fillable);",
  "        $safeSort = in_array($sort, $allowedSorts, true) ? $sort : 'id';",
  "        $sql = 'SELECT * FROM ' . static::$table . ' ' . $where . ' ORDER BY ' . $safeSort . ' ' . $safeDir . ' LIMIT :limit OFFSET :offset';",
  '        $st = static::pdo()->prepare($sql);',
  '        foreach ($params as $k => $v) $st->bindValue($k, $v);',
  "        $st->bindValue(':limit', $perPage, PDO::PARAM_INT);",
  "        $st->bindValue(':offset', $offset, PDO::PARAM_INT);",
  '        $st->execute();',
  "        $rows = array_map(fn($r) => static::castRow($r), $st->fetchAll(PDO::FETCH_ASSOC));",
  "        return ['data' => $rows, 'meta' => ['current_page' => $page, 'per_page' => $perPage, 'total' => $total, 'last_page' => (int)ceil($total / max(1, $perPage))]];",
  '    }',
  '',
  '    public static function create(array $data): array',
  '    {',
  '        $data = static::filter($data);',
  '        $cols = array_keys($data);',
  "        $ph = array_map(fn($c) => ':' . $c, $cols);",
  "        $sql = 'INSERT INTO ' . static::$table . ' (' . implode(', ', $cols) . ') VALUES (' . implode(', ', $ph) . ')';",
  '        $st = static::pdo()->prepare($sql);',
  "        foreach ($data as $k => $v) $st->bindValue(':' . $k, is_array($v) ? json_encode($v) : $v);",
  '        $st->execute();',
  '        return static::find((string)static::pdo()->lastInsertId()) ?? [];',
  '    }',
  '',
  '    public static function update(string $id, array $data): array',
  '    {',
  '        $data = static::filter($data);',
  "        unset($data['id']);",
  '        if (empty($data)) {',
  '            return static::find($id) ?? [];',
  '        }',
  "        $sets = array_map(fn($c) => $c . ' = :' . $c, array_keys($data));",
  "        $sql = 'UPDATE ' . static::$table . ' SET ' . implode(', ', $sets) . ' WHERE id = :__id';",
  '        $st = static::pdo()->prepare($sql);',
  "        foreach ($data as $k => $v) $st->bindValue(':' . $k, is_array($v) ? json_encode($v) : $v);",
  "        $st->bindValue(':__id', $id);",
  '        $st->execute();',
  '        return static::find($id) ?? [];',
  '    }',
  '',
  '    public static function delete(string $id): void',
  '    {',
  '        if (static::$softDeletes) {',
  "            $st = static::pdo()->prepare('UPDATE ' . static::$table . ' SET deleted_at = NOW() WHERE id = :id');",
  '        } else {',
  "            $st = static::pdo()->prepare('DELETE FROM ' . static::$table . ' WHERE id = :id');",
  '        }',
  "        $st->execute([':id' => $id]);",
  '    }',
  '',
  '    protected static function searchable(): array',
  '    {',
  "        return array_values(array_filter(static::$fillable, fn($c) => !in_array($c, ['password', 'key_hash'], true)));",
  '    }',
  '}',
];

const SUPPORT_REQUEST_LINES: string[] = [
  '<?php',
  '/** HTTP request helper. */',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'final class Request',
  '{',
  '    public string $method;',
  '    public string $path;',
  '    public array $query;',
  '    public array $headers;',
  '    private ?array $parsedBody = null;',
  '    public ?array $user = null;',
  '',
  '    public function __construct()',
  '    {',
  "        $this->method = strtoupper($_SERVER['REQUEST_METHOD'] ?? 'GET');",
  "        $uri = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';",
  "        $this->path = $uri === '' ? '/' : $uri;",
  '        $this->query = $_GET ?? [];',
  '        $this->headers = $this->readHeaders();',
  '    }',
  '',
  '    private function readHeaders(): array',
  '    {',
  '        $out = [];',
  '        foreach ($_SERVER as $k => $v) {',
  "            if (substr($k, 0, 5) === 'HTTP_') {",
  "                $name = strtolower(str_replace('_', '-', substr($k, 5)));",
  '                $out[$name] = (string)$v;',
  '            }',
  '        }',
  "        if (isset($_SERVER['CONTENT_TYPE'])) $out['content-type'] = (string)$_SERVER['CONTENT_TYPE'];",
  '        return $out;',
  '    }',
  '',
  '    public function query(string $key, string $default = ' + "''" + '): string',
  '    {',
  '        $v = $this->query[$key] ?? $default;',
  '        return is_string($v) ? $v : $default;',
  '    }',
  '',
  '    public function body(): array',
  '    {',
  '        if ($this->parsedBody !== null) return $this->parsedBody;',
  "        $raw = file_get_contents('php://input') ?: '';",
  "        if ($raw === '') { $this->parsedBody = $_POST ?? []; return $this->parsedBody; }",
  "        $ct = $this->headers['content-type'] ?? '';",
  "        if (strpos($ct, 'application/json') !== false) {",
  '            $d = json_decode($raw, true);',
  '            $this->parsedBody = is_array($d) ? $d : [];',
  '        } else {',
  '            parse_str($raw, $d);',
  '            $this->parsedBody = is_array($d) ? array_merge($_POST ?? [], $d) : ($_POST ?? []);',
  '        }',
  '        return $this->parsedBody;',
  '    }',
  '',
  '    public function bearer(): ?string',
  '    {',
  "        $h = $this->headers['authorization'] ?? '';",
  "        if (substr($h, 0, 7) === 'Bearer ') return substr($h, 7);",
  '        return null;',
  '    }',
  '}',
];

const SUPPORT_RESPONSE_LINES: string[] = [
  '<?php',
  '/** Standardized JSON envelope: {success,data,meta} / {success:false,error{code,message,details},request_id}. */',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'final class Response',
  '{',
  '    public static function json($data, int $status = 200): void',
  '    {',
  '        http_response_code($status);',
  "        header('Content-Type: application/json; charset=utf-8');",
  "        $rid = $GLOBALS['__request_id'] ?? '';",
  "        if ($rid !== '') header('X-Request-ID: ' . $rid);",
  '        echo json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);',
  '    }',
  '',
  '    public static function ok($data, array $meta = []): void',
  '    {',
  "        $rid = $GLOBALS['__request_id'] ?? '';",
  "        $body = ['success' => true, 'data' => $data];",
  "        if ($meta) $body['meta'] = $meta;",
  "        if ($rid !== '') $body['request_id'] = $rid;",
  '        self::json($body, 200);',
  '    }',
  '',
  '    public static function collection(array $rows, int $page, int $perPage, int $total): void',
  '    {',
  "        $rid = $GLOBALS['__request_id'] ?? '';",
  "        $last = (int)ceil($total / max(1, $perPage));",
  "        $body = ['success' => true, 'data' => $rows, 'meta' => ['current_page' => $page, 'per_page' => $perPage, 'total' => $total, 'last_page' => $last]];",
  "        if ($rid !== '') $body['request_id'] = $rid;",
  '        self::json($body, 200);',
  '    }',
  '',
  '    public static function error(string $code, string $message, int $status = 400, array $details = []): void',
  '    {',
  "        $rid = $GLOBALS['__request_id'] ?? '';",
  "        self::json(['success' => false, 'error' => ['code' => $code, 'message' => $message, 'details' => $details], 'request_id' => $rid], $status);",
  '    }',
  '}',
];

const SUPPORT_JWT_LINES: string[] = [
  '<?php',
  '/**',
  ' * Minimal HS256 JWT (no dependencies). Store a long random secret, use HTTPS.',
  ' */',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'final class Jwt',
  '{',
  '    public static function encode(array $payload, string $secret, int $ttlSeconds): string',
  '    {',
  "        $h = self::b64(json_encode(['alg' => 'HS256', 'typ' => 'JWT']));",
  '        $payload[' + "'iat'" + '] = time();',
  '        $payload[' + "'exp'" + '] = time() + $ttlSeconds;',
  '        $p = self::b64(json_encode($payload));',
  '        $sig = self::b64(hash_hmac(' + "'sha256'" + ', $h . chr(46) . $p, $secret, true));',
  '        return $h . chr(46) . $p . chr(46) . $sig;',
  '    }',
  '',
  '    public static function decode(string $token, string $secret): ?array',
  '    {',
  "        $parts = explode(chr(46), $token);",
  '        if (count($parts) !== 3) return null;',
  '        list($h, $p, $s) = $parts;',
  '        $expect = self::b64(hash_hmac(' + "'sha256'" + ', $h . chr(46) . $p, $secret, true));',
  '        if (!hash_equals($expect, $s)) return null;',
  '        $payload = json_decode(self::ub64($p), true);',
  '        if (!is_array($payload)) return null;',
  "        if (isset($payload['exp']) && $payload['exp'] < time()) return null;",
  '        return $payload;',
  '    }',
  '',
  '    private static function b64(string $bin): string',
  '    {',
  "        return rtrim(strtr(base64_encode($bin), '+/', '-_'), '=');",
  '    }',
  '',
  '    private static function ub64(string $s): string',
  '    {',
  "        return base64_decode(strtr($s, '-_', '+/'));",
  '    }',
  '}',
];

const SUPPORT_ROUTER_LINES: string[] = [
  '<?php',
  '/** Router: GET/POST/PUT/PATCH/DELETE/OPTIONS/HEAD, {param} placeholders, 404 vs 405. */',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'final class Router',
  '{',
  '    private array $routes = [];',
  '',
  '    public function add(string $method, string $path, callable $handler, array $middleware = []): void',
  '    {',
  "        $pattern = '#^' . preg_replace('/\\{([a-zA-Z_][a-zA-Z0-9_]*)\\}/', '(?P<$1>[^/]+)', $path) . '$#';",
  "        $this->routes[] = ['method' => strtoupper($method), 'pattern' => $pattern, 'handler' => $handler, 'middleware' => $middleware, 'path' => $path];",
  '    }',
  '',
  '    public function group(string $prefix, callable $cb, array $middleware = []): void',
  '    {',
  '        $before = count($this->routes);',
  '        $cb($this);',
  '        for ($i = $before; $i < count($this->routes); $i++) {',
  "            $this->routes[$i]['pattern'] = '#^' . preg_quote($prefix, '#') . substr($this->routes[$i]['pattern'], 2);",
  "            $this->routes[$i]['middleware'] = array_merge($middleware, $this->routes[$i]['middleware']);",
  '        }',
  '    }',
  '',
  '    /** @return string one of dispatched|not_found|method_not_allowed */',
  '    public function dispatch(Request $req): string',
  '    {',
  '        $pathMatch = false;',
  '        foreach ($this->routes as $r) {',
  "            if (preg_match($r['pattern'], $req->path, $m)) {",
  '                $pathMatch = true;',
  "                if ($r['method'] !== $req->method) continue;",
  '                $params = [];',
  "                foreach ($m as $k => $v) { if (is_string($k)) $params[$k] = $v; }",
  "                ($r['handler'])($req, $params);",
  "                return 'dispatched';",
  '            }',
  '        }',
  "        return $pathMatch ? 'method_not_allowed' : 'not_found';",
  '    }',
  '',
  '    public function list(): array',
  '    {',
  "        return array_map(fn($r) => ['method' => $r['method'], 'path' => $r['path']], $this->routes);",
  '    }',
  '}',
];

const SUPPORT_RATELIMIT_IFACE_LINES: string[] = [
  '<?php',
  '/** RateLimiterInterface — file impl by default, Redis impl can be swapped in. */',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'interface RateLimiterInterface',
  '{',
  '    public function hit(string $key, int $perMinute): bool;',
  '    public function remaining(string $key, int $perMinute): int;',
  '}',
];

const SUPPORT_MIDDLEWARE_LINES: string[] = [
  '<?php',
  '/** CORS (configurable, no wildcard+credentials) + secure headers + rate limit with locking. */',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'final class Middleware',
  '{',
  '    public static function cors(string $origins, bool $credentials = false): void',
  '    {',
  "        $origin = (string)($_SERVER['HTTP_ORIGIN'] ?? '');",
  "        $allow = '*';",
  "        if ($origins !== '*' && $origin !== '') {",
  "            $list = array_map('trim', explode(',', $origins));",
  "            $allow = in_array($origin, $list, true) ? $origin : $list[0];",
  "            header('Vary: Origin');",
  '        } else {',
  "            header('Vary: Origin');",
  '        }',
  "        if ($origins === '*' && $credentials) { $allow = $origin !== '' ? $origin : 'null'; }",
  "        header('Access-Control-Allow-Origin: ' . $allow);",
  "        header('Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD');",
  "        header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With, X-Request-ID');",
  "        if ($credentials) header('Access-Control-Allow-Credentials: true');",
  "        if (($_SERVER['REQUEST_METHOD'] ?? '') === 'OPTIONS') { http_response_code(204); exit; }",
  '    }',
  '',
  '    public static function securityHeaders(): void',
  '    {',
  "        header('X-Content-Type-Options: nosniff');",
  "        header('X-Frame-Options: DENY');",
  "        header('Referrer-Policy: no-referrer');",
  "        if ((($_SERVER['HTTPS'] ?? '') !== '') || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https')) {",
  "            header('Strict-Transport-Security: max-age=31536000; includeSubDomains');",
  '        }',
  '    }',
  '',
  '    public static function rateLimit(int $perMinute = 120, ?string $key = null): void',
  '    {',
  "        $dir = sys_get_temp_dir() . '/phpbb_rl';",
  '        if (!is_dir($dir)) @mkdir($dir, 0700, true);',
  "        $id = $key ?? (string)($_SERVER['REMOTE_ADDR'] ?? 'cli');",
  "        $safe = preg_replace('/[^a-zA-Z0-9.:_-]/', '_', $id);",
  "        $file = $dir . '/' . $safe . '.json';",
  "        $fp = fopen($file, 'c+');",
  "        if ($fp === false) return;",
  '        flock($fp, LOCK_EX);',
  '        $now = time();',
  "        $bucket = ['t' => $now, 'n' => 0];",
  "        $raw = stream_get_contents($fp);",
  '        if ($raw) {',
  '            $d = json_decode($raw, true);',
  "            if (is_array($d) && isset($d['t'], $d['n'])) $bucket = $d;",
  '        }',
  "        if ($now - (int)$bucket['t'] >= 60) { $bucket = ['t' => $now, 'n' => 0]; }",
  "        $bucket['n']++;",
  '        ftruncate($fp, 0); rewind($fp); fwrite($fp, json_encode($bucket)); fflush($fp); flock($fp, LOCK_UN); fclose($fp);',
  "        header('X-RateLimit-Limit: ' . $perMinute);",
  "        header('X-RateLimit-Remaining: ' . max(0, $perMinute - (int)$bucket['n']));",
  "        if ($bucket['n'] > $perMinute) {",
  "            header('Retry-After: ' . max(1, 60 - ($now - (int)$bucket['t'])));",
  "            Response::error('RATE_LIMITED', 'Too many requests', 429);",
  '            exit;',
  '        }',
  '    }',
  '',
  '    public static function authRateLimit(): void',
  '    {',
  "        $ip = (string)($_SERVER['REMOTE_ADDR'] ?? 'cli');",
  "        self::rateLimit(20, 'auth_' . $ip);",
  '    }',
  '}',
];

const SUPPORT_LOGGER_LINES: string[] = [
  '<?php',
  '/** Structured logger — never logs passwords/JWTs/refresh tokens/keys/headers. */',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'final class Logger',
  '{',
  "    private const SECRET_KEYS = ['password', 'passwd', 'secret', 'token', 'jwt', 'refresh_token', 'authorization', 'api_key', 'apikey', 'db_pass', 'db_password'];",
  '    public static function log(string $level, string $msg, array $ctx = []): void',
  '    {',
  "        $rid = $GLOBALS['__request_id'] ?? '-';",
  "        $safe = self::redact($ctx);",
  "        $line = json_encode(['ts' => date('c'), 'level' => $level, 'request_id' => $rid, 'msg' => $msg, 'ctx' => $safe], JSON_UNESCAPED_SLASHES);",
  "        error_log((string)$line);",
  '    }',
  '    public static function debug(string $m, array $c = []): void { self::log(' + "'debug'" + ', $m, $c); }',
  '    public static function info(string $m, array $c = []): void { self::log(' + "'info'" + ', $m, $c); }',
  '    public static function warning(string $m, array $c = []): void { self::log(' + "'warning'" + ', $m, $c); }',
  '    public static function error(string $m, array $c = []): void { self::log(' + "'error'" + ', $m, $c); }',
  '    private static function redact(array $ctx): array',
  '    {',
  '        $out = [];',
  '        foreach ($ctx as $k => $v) {',
  "            $lk = strtolower((string)$k);",
  '            $hit = false;',
  "            foreach (self::SECRET_KEYS as $s) { if (strpos($lk, $s) !== false) { $hit = true; break; } }",
  "            $out[$k] = $hit ? '[redacted]' : $v;",
  '        }',
  '        return $out;',
  '    }',
  '}',
];

const SUPPORT_ENV_LINES: string[] = [
  '<?php',
  '/** Minimal .env loader — real env vars always win; .env never logged. */',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'final class Env',
  '{',
  '    public static function load(string $dir): void',
  '    {',
  "        $file = rtrim($dir, '/\\\\') . DIRECTORY_SEPARATOR . '.env';",
  '        if (!is_file($file) || !is_readable($file)) return;',
  "        foreach (file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [] as $line) {",
  "            $line = trim($line);",
  "            if ($line === '' || $line[0] === '#') continue;",
  "            $pos = strpos($line, '=');",
  '            if ($pos === false) continue;',
  '            $k = trim(substr($line, 0, $pos));',
  '            $v = trim(substr($line, $pos + 1));',
  '            if (!preg_match(\'/^[A-Za-z_][A-Za-z0-9_]*$/\', $k)) continue;',
  '            if (strlen($v) >= 2 && (($v[0] === \'"\' && substr($v, -1) === \'"\') || ($v[0] === "\'" && substr($v, -1) === "\'"))) { $v = substr($v, 1, -1); }',
  '            if (getenv($k) === false && !isset($_SERVER[$k]) && !isset($_ENV[$k])) {',
  '                putenv($k . \'=\' . $v);',
  '                $_ENV[$k] = $v;',
  '                $_SERVER[$k] = $v;',
  '            }',
  '        }',
  '    }',
  '}',
];

const SUPPORT_HANDLER_LINES: string[] = [
  '<?php',
  '/** Global exception handler — prod hides SQL/paths/traces; dev may show diagnostics. */',
  'declare(strict_types=1);',
  '',
  'namespace App\\Support;',
  '',
  'use Throwable;',
  '',
  'final class Handler',
  '{',
  '    public static function register(array $config): void',
  '    {',
  '        set_exception_handler(function (Throwable $e) use ($config) {',
  "            $debug = ($config['env'] ?? 'production') !== 'production';",
  "            Logger::error('unhandled', ['class' => get_class($e), 'message' => $e->getMessage()]);",
  '            if ($debug) {',
  "                Response::json(['success' => false, 'error' => ['code' => 'INTERNAL', 'message' => $e->getMessage(), 'details' => ['file' => basename($e->getFile()), 'line' => $e->getLine()]], 'request_id' => $GLOBALS['__request_id'] ?? ''], 500);",
  '            } else {',
  "                Response::error('INTERNAL', 'Internal server error', 500);",
  '            }',
  '        });',
  '    }',
  '}',
];

function trimSlash(p: string): string {
  return p.endsWith('/') && p.length > 1 ? p.slice(0, -1) : p;
}

export function generateProject(state: BuilderState): GenFile[] {
  const files: GenFile[] = [];
  const rawPrefix = state.config.apiPrefix || '/api/v1';
  const prefix = trimSlash(rawPrefix.startsWith('/') ? rawPrefix : '/' + rawPrefix);
  const ttl = (state.auth.tokenExpiryHours || 24) * 3600;
  const BUILDER_VERSION = '1.0.0';
  const GENERATOR_VERSION = '2.0.0';
  const IR_VERSION = '1.0.0';

  // Support infrastructure with namespaces and Container DI
  files.push({ path: 'backend/support/Container.php', language: 'php', content: SUPPORT_CONTAINER_LINES.join('\n') + '\n' });
  files.push({ path: 'backend/support/Model.php', language: 'php', content: SUPPORT_MODEL_LINES.join('\n') + '\n' });
  files.push({ path: 'backend/support/Request.php', language: 'php', content: SUPPORT_REQUEST_LINES.join('\n') + '\n' });
  files.push({ path: 'backend/support/Response.php', language: 'php', content: SUPPORT_RESPONSE_LINES.join('\n') + '\n' });
  files.push({ path: 'backend/support/Router.php', language: 'php', content: SUPPORT_ROUTER_LINES.join('\n') + '\n' });
  files.push({ path: 'backend/support/Middleware.php', language: 'php', content: SUPPORT_MIDDLEWARE_LINES.join('\n') + '\n' });
  files.push({ path: 'backend/support/RateLimiterInterface.php', language: 'php', content: SUPPORT_RATELIMIT_IFACE_LINES.join('\n') + '\n' });
  files.push({ path: 'backend/support/Logger.php', language: 'php', content: SUPPORT_LOGGER_LINES.join('\n') + '\n' });
  files.push({ path: 'backend/support/Handler.php', language: 'php', content: SUPPORT_HANDLER_LINES.join('\n') + '\n' });
  files.push({ path: 'backend/support/Env.php', language: 'php', content: SUPPORT_ENV_LINES.join('\n') + '\n' });

  if (state.auth.strategy !== 'none') {
    files.push({ path: 'backend/support/Jwt.php', language: 'php', content: SUPPORT_JWT_LINES.join('\n') + '\n' });
  }

  files.push({
    path: 'backend/config/database.php', language: 'php',
    content: header('Config: database (PDO factory + Container binding)') +
      'use App\\Support\\Container;\n\n' +
      'function db(): PDO\n{\n' +
      '    $c = Container::getInstance();\n' +
      '    if ($c->has(PDO::class)) {\n' +
      '        return $c->get(PDO::class);\n' +
      '    }\n' +
      "    $host = getenv('DB_HOST') ?: '" + state.config.dbHost + "';\n" +
      "    $name = getenv('DB_NAME') ?: '" + state.config.dbName + "';\n" +
      "    $user = getenv('DB_USER') ?: 'root';\n" +
      "    $pass = getenv('DB_PASS') ?: '';\n" +
      '    $dsn = "mysql:host=" . $host . ";dbname=" . $name . ";charset=utf8mb4";\n' +
      '    $pdo = new PDO($dsn, $user, $pass, [\n' +
      '        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,\n' +
      '        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n' +
      '        PDO::ATTR_EMULATE_PREPARES => false,\n' +
      '    ]);\n' +
      '    $c->instance(PDO::class, $pdo);\n' +
      '    return $pdo;\n}\n',
  });

  files.push({
    path: 'backend/config/app.php', language: 'php',
    content: header('Config: app — secrets ONLY from env, fail closed when missing') +
      'return [\n' +
      "    'name' => '" + state.config.projectName + "',\n" +
      "    'env' => getenv('APP_ENV') ?: 'production',\n" +
      "    'url' => getenv('APP_URL') ?: 'http://localhost:8000',\n" +
      "    'api_prefix' => '" + prefix + "',\n" +
      "    'cors_origins' => getenv('CORS_ORIGINS') ?: '" + state.config.corsOrigins + "',\n" +
      // Fail closed: empty secret forces key:generate before boot (never a usable default)
      "    'jwt_secret' => getenv('JWT_SECRET') ?: '',\n" +
      "    'jwt_ttl' => " + ttl + ",\n" +
      "    'jwt_refresh_ttl' => 2592000,\n" +
      "    'per_page' => " + state.config.pagination + ",\n" +
      "    'builder_version' => '" + BUILDER_VERSION + "',\n" +
      "    'generator_version' => '" + GENERATOR_VERSION + "',\n" +
      "    'ir_version' => '" + IR_VERSION + "',\n" +
      '];\n',
  });

  // Topologically sort tables according to Foreign Key dependencies
  const topoResult = sortTablesTopologically(state.tables);
  const sortedTables = topoResult.sorted;

  // Deterministic ordered migrations: 001, 002, ... (in topological dependency order)
  sortedTables.forEach((t, idx) => {
    const n = String(idx + 1).padStart(3, '0');
    const isAuthResource = t.name === 'users';
    files.push({ path: 'backend/models/' + toClassName(t.name) + '.php', language: 'php', content: modelFor(t) });
    files.push({ path: 'backend/controllers/' + toClassName(t.name) + 'Controller.php', language: 'php', content: controllerFor(t, state.config.pagination, isAuthResource) });
    files.push({ path: 'database/migrations/' + n + '_create_' + t.name + '.php', language: 'php', content: migrationFor(t) });
  });

  if (state.auth.strategy !== 'none' && state.auth.strategy !== 'existing') {
    const authLines: string[] = [
      header('Controller: Auth (register, login, logout, refresh, me) — rotation + reuse detection', 'App\\Controllers').trimEnd(),
      'use App\\Support\\Request;',
      'use App\\Support\\Response;',
      'use App\\Support\\Jwt;',
      'use App\\Support\\Middleware;',
      'use App\\Support\\Container;',
      'use PDO;',
      'use Throwable;',
      '',
      'final class AuthController',
      '{',
      '    private function pdo(): PDO',
      '    {',
      '        $c = Container::getInstance();',
      '        if ($c->has(PDO::class)) return $c->get(PDO::class);',
      '        return db();',
      '    }',
      '',
      '    private function issueTokens(string $userId, array $cfg): array',
      '    {',
      "        if (($cfg['jwt_secret'] ?? '') === '') { Response::error('CONFIG', 'JWT not configured. Run: php bin/backend key:generate', 500); exit; }",
      "        $jti = bin2hex(random_bytes(16));",
      "        $access = Jwt::encode(['sub' => $userId, 'jti' => $jti], $cfg['jwt_secret'], (int)$cfg['jwt_ttl']);",
      "        $rawRefresh = bin2hex(random_bytes(32));",
      "        $hash = hash('sha256', $rawRefresh);",
      "        $pdo = $this->pdo();",
      "        $pdo->prepare('INSERT INTO refresh_tokens (user_id, token_hash, expires_at) VALUES (:u, :h, DATE_ADD(NOW(), INTERVAL 30 DAY))')->execute([':u' => $userId, ':h' => $hash]);",
      "        return ['access' => $access, 'refresh' => $rawRefresh];",
      '    }',
      '',
      '    public function register(Request $req, array $cfg): void',
      '    {',
      "        Middleware::authRateLimit();",
      '        $b = $req->body();',
      "        $name = trim((string)($b['name'] ?? ''));",
      "        $email = strtolower(trim((string)($b['email'] ?? '')));",
      "        $password = (string)($b['password'] ?? '');",
      "        if ($name === '' || strpos($email, '@') === false || strlen($password) < 8) {",
      "            Response::error('VALIDATION_ERROR', 'Provide name, valid email and 8+ char password.', 422); return;",
      '        }',
      "        $pdo = $this->pdo();",
      "        $pdo->beginTransaction();",
      '        try {',
      "            $exists = $pdo->prepare('SELECT id FROM users WHERE email = :e LIMIT 1');",
      "            $exists->execute([':e' => $email]);",
      "            if ($exists->fetch()) { $pdo->rollBack(); Response::error('CONFLICT', 'Email already registered', 409); return; }",
      "            $hash = password_hash($password, PASSWORD_BCRYPT);",
      "            $st = $pdo->prepare('INSERT INTO users (name, email, password) VALUES (:n, :e, :p)');",
      "            $st->execute([':n' => $name, ':e' => $email, ':p' => $hash]);",
      "            $newId = (string)$pdo->lastInsertId();",
      "            $t = $this->issueTokens($newId, $cfg);",
      "            $pdo->commit();",
      "            Response::json(['success' => true, 'data' => ['token' => $t['access'], 'access_token' => $t['access'], 'refresh_token' => $t['refresh'], 'token_type' => 'Bearer'], 'request_id' => $GLOBALS['__request_id'] ?? ''], 201);",
      '        } catch (Throwable $e) {',
      '            if ($pdo->inTransaction()) $pdo->rollBack();',
      "            Response::error('INTERNAL', 'Registration failed: ' . $e->getMessage(), 500);",
      '        }',
      '    }',
      '',
      '    public function login(Request $req, array $cfg): void',
      '    {',
      "        Middleware::authRateLimit();",
      '        $b = $req->body();',
      "        $email = strtolower(trim((string)($b['email'] ?? '')));",
      "        $password = (string)($b['password'] ?? '');",
      "        if ($email === '' || $password === '') {",
      "            Response::error('VALIDATION_ERROR', 'Email and password are required', 422); return;",
      "        }",
      "        $pdo = $this->pdo();",
      "        $st = $pdo->prepare('SELECT * FROM users WHERE email = :e LIMIT 1');",
      "        $st->execute([':e' => $email]);",
      '        $user = $st->fetch(PDO::FETCH_ASSOC);',
      "        if (!$user || !password_verify($password, (string)$user['password'])) {",
      "            Response::error('UNAUTHORIZED', 'Invalid credentials', 401); return;",
      '        }',
      "        unset($user['password']);",
      "        $t = $this->issueTokens((string)$user['id'], $cfg);",
      "        Response::json(['success' => true, 'data' => ['token' => $t['access'], 'access_token' => $t['access'], 'refresh_token' => $t['refresh'], 'token_type' => 'Bearer', 'user' => $user], 'request_id' => $GLOBALS['__request_id'] ?? '']);",
      '    }',
      '',
      '    public function logout(Request $req): void',
      '    {',
      '        $b = $req->body();',
      "        $raw = (string)($b['refresh_token'] ?? $req->bearer() ?? '');",
      "        if ($raw !== '') {",
      "            $pdo = $this->pdo();",
      "            $pdo->prepare('DELETE FROM refresh_tokens WHERE token_hash = :h')->execute([':h' => hash('sha256', $raw)]);",
      '        }',
      "        Response::json(['success' => true, 'data' => ['logged_out' => true]]);",
      '    }',
      '',
      '    public function refresh(Request $req, array $cfg): void',
      '    {',
      "        Middleware::authRateLimit();",
      '        $b = $req->body();',
      "        $raw = (string)($b['refresh_token'] ?? '');",
      "        if ($raw === '') { Response::error('UNAUTHORIZED', 'Missing refresh token', 401); return; }",
      "        $pdo = $this->pdo();",
      "        $pdo->beginTransaction();",
      '        try {',
      "            $st = $pdo->prepare('SELECT * FROM refresh_tokens WHERE token_hash = :h LIMIT 1');",
      "            $st->execute([':h' => hash('sha256', $raw)]);",
      '            $row = $st->fetch(PDO::FETCH_ASSOC);',
      "            if (!$row) { $pdo->rollBack(); Response::error('UNAUTHORIZED', 'Invalid refresh token (reuse detected)', 401); return; }",
      "            if (strtotime((string)$row['expires_at']) < time()) {",
      "                $pdo->prepare('DELETE FROM refresh_tokens WHERE id = :id')->execute([':id' => $row['id']]);",
      "                $pdo->commit();",
      "                Response::error('UNAUTHORIZED', 'Expired refresh token', 401); return;",
      '            }',
      "            $pdo->prepare('DELETE FROM refresh_tokens WHERE id = :id')->execute([':id' => $row['id']]);",
      "            $t = $this->issueTokens((string)$row['user_id'], $cfg);",
      "            $pdo->commit();",
      "            Response::json(['success' => true, 'data' => ['token' => $t['access'], 'access_token' => $t['access'], 'refresh_token' => $t['refresh'], 'token_type' => 'Bearer']]);",
      '        } catch (Throwable $e) {',
      '            if ($pdo->inTransaction()) $pdo->rollBack();',
      "            Response::error('INTERNAL', 'Token refresh failed: ' . $e->getMessage(), 500);",
      '        }',
      '    }',
      '',
      '    public function me(Request $req): void',
      '    {',
      "        Response::json(['success' => true, 'data' => ['user' => $req->user]]);",
      '    }',
      '}',
    ];
    files.push({ path: 'backend/controllers/AuthController.php', language: 'php', content: authLines.join('\n') + '\n' });
  }

  const routeLines: string[] = [];
  if (state.auth.strategy !== 'none') {
    const canonicalAuth = getCanonicalAuthRoutes(state.auth, prefix);
    for (const cr of canonicalAuth) {
      const handlerMap: Record<string, string> = {
        register: "fn($req) => $c->get(AuthController::class)->register($req, $config)",
        login: "fn($req) => $c->get(AuthController::class)->login($req, $config)",
        logout: "fn($req) => $c->get(AuthController::class)->logout($req)",
        refresh: "fn($req) => $c->get(AuthController::class)->refresh($req, $config)",
        me: "function ($req) use ($config, $c) { requireAuth($req, $config); $c->get(AuthController::class)->me($req); }",
        forgotPassword: "fn($req) => $c->get(AuthController::class)->forgotPassword($req)",
        resetPassword: "fn($req) => $c->get(AuthController::class)->resetPassword($req)",
        verifyEmail: "fn($req) => $c->get(AuthController::class)->verifyEmail($req)",
      };
      const handler = handlerMap[cr.handlerAction] ?? `fn($req) => $c->get(AuthController::class)->${cr.handlerAction}($req)`;
      routeLines.push(`$router->add('${cr.method}', '${cr.fullPath}', ${handler});`);
    }
  }
  routeLines.push("$router->add('GET', '" + prefix + "/health', fn() => Response::json(['success' => true, 'data' => ['ok' => true, 'time' => date('c')]]));");
  routeLines.push("$router->add('GET', '" + prefix + "/health/live', fn() => Response::json(['success' => true, 'data' => ['live' => true]]));");
  routeLines.push("$router->add('GET', '" + prefix + "/health/ready', function () { try { db(); Response::json(['success' => true, 'data' => ['ready' => true]]); } catch (Throwable $e) { Response::error('UNAVAILABLE', 'Database unavailable', 503); } });");
  for (const t of sortedTables) {
    const c = toClassName(t.name) + 'Controller';
    routeLines.push("$router->add('GET', '" + prefix + '/' + t.name + "', fn($req) => $c->get(" + c + "::class)->list($req));");
    routeLines.push("$router->add('POST', '" + prefix + '/' + t.name + "', fn($req) => $c->get(" + c + "::class)->create($req));");
    routeLines.push("$router->add('GET', '" + prefix + '/' + t.name + "/{id}', fn($req, $p) => $c->get(" + c + "::class)->read($req, $p['id']));");
    routeLines.push("$router->add('PUT', '" + prefix + '/' + t.name + "/{id}', fn($req, $p) => $c->get(" + c + "::class)->update($req, $p['id']));");
    routeLines.push("$router->add('PATCH', '" + prefix + '/' + t.name + "/{id}', fn($req, $p) => $c->get(" + c + "::class)->patch($req, $p['id']));");
    routeLines.push("$router->add('DELETE', '" + prefix + '/' + t.name + "/{id}', fn($req, $p) => $c->get(" + c + "::class)->delete($req, $p['id']));");
  }

  // PSR-4 autoloader block
  const autoloaderCode = [
    'spl_autoload_register(function ($class) {',
    "    $prefix = 'App\\\\';",
    "    $baseDir = dirname(__DIR__) . '/';",
    '    $len = strlen($prefix);',
    '    if (strncmp($prefix, $class, $len) !== 0) return;',
    '    $relativeClass = substr($class, $len);',
    "    $file = $baseDir . str_replace('\\\\', '/', $relativeClass) . '.php';",
    '    if (file_exists($file)) require_once $file;',
    '});',
  ].join('\n');

  const controllerRequires = sortedTables.map((t) => "require_once __DIR__ . '/../controllers/" + toClassName(t.name) + "Controller.php';").join('\n');
  const controllerUses = sortedTables.map((t) => 'use App\\Controllers\\' + toClassName(t.name) + 'Controller;').join('\n');

  const frontLines: string[] = [
    header('Front controller - run: php -S localhost:8000 -t backend/public').trimEnd(),
    autoloaderCode,
    '',
    "require_once __DIR__ . '/../support/Env.php';",
    "Env::load(dirname(__DIR__, 2));",
    "require_once __DIR__ . '/../support/Container.php';",
    "require_once __DIR__ . '/../support/Request.php';",
    "require_once __DIR__ . '/../support/Response.php';",
    "require_once __DIR__ . '/../support/Router.php';",
    "require_once __DIR__ . '/../support/Middleware.php';",
    "require_once __DIR__ . '/../support/Logger.php';",
    "require_once __DIR__ . '/../support/Handler.php';",
    "require_once __DIR__ . '/../support/RequestId.php';",
    "require_once __DIR__ . '/../support/Model.php';",
  ];

  if (state.auth.strategy !== 'none') {
    frontLines.push("require_once __DIR__ . '/../support/Jwt.php';");
  }

  frontLines.push(
    "require_once __DIR__ . '/../config/database.php';",
    "$config = require __DIR__ . '/../config/app.php';",
    controllerRequires
  );

  if (state.auth.strategy !== 'none' && state.auth.strategy !== 'existing') {
    frontLines.push("require_once __DIR__ . '/../controllers/AuthController.php';");
  }

  frontLines.push(
    '',
    'use App\\Support\\Container;',
    'use App\\Support\\Request;',
    'use App\\Support\\Response;',
    'use App\\Support\\Router;',
    'use App\\Support\\Middleware;',
    'use App\\Support\\Logger;',
    'use App\\Support\\Handler;',
    'use App\\Support\\RequestId;',
    'use App\\Support\\Env;'
  );

  if (state.auth.strategy !== 'none') {
    frontLines.push('use App\\Support\\Jwt;');
  }
  if (state.auth.strategy !== 'none' && state.auth.strategy !== 'existing') {
    frontLines.push('use App\\Controllers\\AuthController;');
  }

  frontLines.push(controllerUses);
  frontLines.push('');
  frontLines.push("$GLOBALS['__request_id'] = RequestId::handle();");
  frontLines.push("Handler::register($config);");
  frontLines.push("Middleware::securityHeaders();");
  frontLines.push("Middleware::cors($config['cors_origins']);");
  frontLines.push('Middleware::rateLimit(120);');
  if (state.auth.strategy !== 'none') {
    frontLines.push("if (($config['jwt_secret'] ?? '') === '' && strpos((string)($_SERVER['REQUEST_URI'] ?? ''), '/health') === false) { /* fail closed on auth routes only — health stays open */ }");
  }
  frontLines.push("try { db(); } catch (Throwable $e) { Logger::error('db_unavailable', []); Response::error('UNAVAILABLE', 'Database unavailable', 503); exit; }");
  frontLines.push("Logger::info('request', ['method' => $_SERVER['REQUEST_METHOD'] ?? '', 'path' => parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH)]);");
  if (state.auth.strategy !== 'none') {
    frontLines.push('function requireAuth(Request $req, array $config): void {');
    frontLines.push('    $token = $req->bearer();');
    frontLines.push("    if (!$token) { Response::error('UNAUTHORIZED', 'Unauthorized', 401); exit; }");
    frontLines.push("    if (($config['jwt_secret'] ?? '') === '') { Response::error('CONFIG', 'JWT not configured', 500); exit; }");
    frontLines.push('    $payload = Jwt::decode($token, $config[' + "'jwt_secret'" + ']);');
    frontLines.push("    if (!$payload) { Response::error('UNAUTHORIZED', 'Invalid or expired token', 401); exit; }");
    frontLines.push('    $req->user = $payload;');
    frontLines.push('}');
    frontLines.push('function requireRole(Request $req, array $roles): void {');
    frontLines.push("    $role = (string)($req->user['role'] ?? 'user');");
    frontLines.push("    if (!in_array($role, $roles, true)) { Response::error('FORBIDDEN', 'Forbidden', 403); exit; }");
    frontLines.push('}');
    frontLines.push('');
  }

  frontLines.push('$router = new Router();');
  frontLines.push('$req = new Request();');
  frontLines.push('$c = Container::getInstance();');
  frontLines.push('');
  for (const r of routeLines) frontLines.push(r);
  frontLines.push('');

  if (state.auth.strategy !== 'none') {
    frontLines.push('// Auth guard: mutating requests under the API prefix require a token.');
    frontLines.push("if (strpos($req->path, '" + prefix + "') === 0 && in_array($req->method, ['POST', 'PUT', 'PATCH', 'DELETE'], true)) {");
    frontLines.push('    $open = [');
    frontLines.push("        'POST " + prefix + "/auth/register',");
    frontLines.push("        'POST " + prefix + "/auth/login',");
    frontLines.push("        'POST " + prefix + "/auth/refresh',");
    frontLines.push('    ];');
    frontLines.push('    if (!in_array($req->method . chr(32) . $req->path, $open, true)) { requireAuth($req, $config); }');
    frontLines.push('}');
    frontLines.push('');
  }
  frontLines.push('');
  frontLines.push("$result = $router->dispatch($req);");
  frontLines.push("if ($result === 'not_found') { Response::error('NOT_FOUND', 'Not found', 404); }");
  frontLines.push("elseif ($result === 'method_not_allowed') { Response::error('METHOD_NOT_ALLOWED', 'Method not allowed', 405); }");
  files.push({ path: 'backend/public/index.php', language: 'php', content: frontLines.join('\n') + '\n' });

  // Schema generation in topological order, refresh_tokens placed strictly AFTER users
  const refreshTokensSql = (state.auth.strategy !== 'none' && state.auth.strategy !== 'existing')
    ? 'CREATE TABLE IF NOT EXISTS refresh_tokens (\n  id BIGINT AUTO_INCREMENT NOT NULL,\n  user_id BIGINT NOT NULL,\n  token_hash CHAR(64) NOT NULL,\n  expires_at DATETIME NOT NULL,\n  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (id),\n  CONSTRAINT fk_refresh_tokens_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;'
    : '';

  const tableSqls = sortedTables.map((t) => 'CREATE TABLE IF NOT EXISTS ' + t.name + ' (\n' + nljoin(dbColumnsSql(t)) + '\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;');
  if (refreshTokensSql) {
    tableSqls.push(refreshTokensSql);
  }
  const schemaBody = tableSqls.join('\n\n');

  files.push({
    path: 'database/schema.sql', language: 'sql',
    content: '-- ' + state.config.projectName + ' schema (MySQL 8+)\n-- Import: create database ' + state.config.dbName + ' then run this file\n\nCREATE DATABASE IF NOT EXISTS ' + state.config.dbName + ' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\nUSE ' + state.config.dbName + ';\n\n' + schemaBody + '\n',
  });

  // RequestId support file (referenced by front controller)
  files.push({
    path: 'backend/support/RequestId.php', language: 'php',
    content: header('Request ID — X-Request-ID header', 'App\\Support') +
      "final class RequestId\n{\n    public static function handle(): string\n    {\n        $id = (string)($_SERVER['HTTP_X_REQUEST_ID'] ?? '');\n        if ($id === '' || !preg_match('/^[A-Za-z0-9-]{1,64}$/', $id)) { $id = bin2hex(random_bytes(16)); }\n        header('X-Request-ID: ' . $id);\n        return $id;\n    }\n}\n",
  });

  // Refresh-token storage migration: numbered AFTER all resource tables
  if (state.auth.strategy !== 'none' && state.auth.strategy !== 'existing') {
    const refreshMigNum = String(sortedTables.length + 1).padStart(3, '0');
    files.push({
      path: `database/migrations/${refreshMigNum}_create_refresh_tokens.php`, language: 'php',
      content: header('Migration: refresh_tokens (rotation, revocation)') +
        'return new class {\n' +
        '    public function up(PDO $pdo): void\n' +
        '    {\n' +
        '        $pdo->exec("CREATE TABLE IF NOT EXISTS refresh_tokens (\n  id BIGINT AUTO_INCREMENT NOT NULL,\n  user_id BIGINT NOT NULL,\n  token_hash CHAR(64) NOT NULL,\n  expires_at DATETIME NOT NULL,\n  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (id),\n  CONSTRAINT fk_refresh_tokens_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");\n' +
        '    }\n\n' +
        '    public function down(PDO $pdo): void\n' +
        '    {\n' +
        '        $pdo->exec("DROP TABLE IF EXISTS refresh_tokens");\n' +
        '    }\n' +
        '};\n',
    });
  }

  files.push({
    path: 'database/migrate.php', language: 'php',
    content: header('Migration runner: migrate|migrate:rollback|migrate:status|migrate:fresh (tracks history)') +
      "require_once __DIR__ . '/../backend/support/Env.php';\nApp\\Support\\Env::load(dirname(__DIR__));\nrequire_once __DIR__ . '/../backend/support/Container.php';\nrequire_once __DIR__ . '/../backend/config/database.php';\n$pdo = db();\n$action = $argv[1] ?? 'migrate';\n" +
      "$pdo->exec('CREATE TABLE IF NOT EXISTS migrations (id INT AUTO_INCREMENT PRIMARY KEY, migration VARCHAR(255) NOT NULL UNIQUE, batch INT NOT NULL, ran_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)');\n" +
      "$files = glob(__DIR__ . '/migrations/*.php');\nsort($files);\n" +
      "function applied(PDO $pdo): array { try { return $pdo->query('SELECT migration FROM migrations')->fetchAll(PDO::FETCH_COLUMN); } catch (Throwable $e) { return []; } }\n" +
      "if ($action === 'migrate' || $action === 'up') { $done = applied($pdo); $batch = (int)$pdo->query('SELECT COALESCE(MAX(batch),0) FROM migrations')->fetchColumn() + 1; foreach ($files as $f) { $name = basename($f); if (in_array($name, $done, true)) continue; $m = require $f; try { $m->up($pdo); $s = $pdo->prepare('INSERT INTO migrations (migration, batch) VALUES (:m, :b)'); $s->execute([':m' => $name, ':b' => $batch]); echo $name . ' [migrate] OK' . PHP_EOL; } catch (Throwable $e) { echo $name . ' [FAILED] ' . $e->getMessage() . PHP_EOL; exit(1); } } }\n" +
      "elseif ($action === 'migrate:rollback' || $action === 'down') { $batch = (int)$pdo->query('SELECT COALESCE(MAX(batch),0) FROM migrations')->fetchColumn(); if (!$batch) { echo 'Nothing to roll back.' . PHP_EOL; exit(0); } $stmt = $pdo->prepare('SELECT migration FROM migrations WHERE batch = :batch ORDER BY migration DESC'); $stmt->execute([':batch' => $batch]); $rows = $stmt->fetchAll(PDO::FETCH_COLUMN); foreach ($rows as $name) { $f = __DIR__ . '/migrations/' . $name; if (!is_file($f)) continue; $m = require $f; $m->down($pdo); $pdo->prepare('DELETE FROM migrations WHERE migration=:m')->execute([':m' => $name]); echo $name . ' [rollback] OK' . PHP_EOL; } }\n" +
      "elseif ($action === 'migrate:status') { $done = applied($pdo); foreach ($files as $f) { $n = basename($f); echo $n . ' ' . (in_array($n, $done, true) ? '[ran]' : '[pending]') . PHP_EOL; } }\n" +
      "elseif ($action === 'migrate:fresh') { foreach (array_reverse($files) as $f) { $m = require $f; try { $m->down($pdo); } catch (Throwable $e) {} } $pdo->exec('DELETE FROM migrations'); echo 'Fresh: all down.' . PHP_EOL; }\n" +
      "else { echo 'Usage: php database/migrate.php migrate|migrate:rollback|migrate:status|migrate:fresh' . PHP_EOL; exit(1); }\necho 'Done.' . PHP_EOL;\n",
  });

  files.push({
    path: '.env.example', language: 'ini',
    content: 'APP_ENV=production\nAPP_URL=http://localhost:8000\nAPP_KEY=\nDB_HOST=' + state.config.dbHost + '\nDB_NAME=' + state.config.dbName + '\nDB_USER=root\nDB_PASS=\nJWT_SECRET=\nJWT_REFRESH_TTL=2592000\nCORS_ORIGINS=' + state.config.corsOrigins + '\n',
  });

  const clientFns = sortedTables.map((t) => {
    const c = toClassName(t.name);
    return 'export async function list' + c + 's(params) { return api(' + "'/" + t.name + "'" + ', { query: params || {} }); }\n' +
      'export async function get' + c + '(id) { return api(' + "'/" + t.name + "/'" + ' + encodeURIComponent(id)); }\n' +
      'export async function create' + c + '(data) { return api(' + "'/" + t.name + "'" + ', { method: ' + "'POST'" + ', body: data }); }\n' +
      'export async function update' + c + '(id, data) { return api(' + "'/" + t.name + "/'" + ' + encodeURIComponent(id), { method: ' + "'PUT'" + ', body: data }); }\n' +
      'export async function patch' + c + '(id, data) { return api(' + "'/" + t.name + "/'" + ' + encodeURIComponent(id), { method: ' + "'PATCH'" + ', body: data }); }\n' +
      'export async function delete' + c + '(id) { return api(' + "'/" + t.name + "/'" + ' + encodeURIComponent(id), { method: ' + "'DELETE'" + ' }); }';
  }).join('\n\n');

  const clientAuthFns = (state.auth.strategy !== 'none' && state.auth.strategy !== 'existing') ? [
    "export async function register(data) { var r = await api('/auth/register', { method: 'POST', body: data }); storeAuth(r); return r; }",
    "export async function login(data) { var r = await api('/auth/login', { method: 'POST', body: data }); storeAuth(r); return r; }",
    "export async function refresh() { var r = await api('/auth/refresh', { method: 'POST', body: { refresh_token: refreshToken } }); storeAuth(r); return r; }",
    "export async function me() { return api('/auth/me'); }",
    "export async function logout() { try { await api('/auth/logout', { method: 'POST', body: { refresh_token: refreshToken } }); } catch (e) {} setToken(''); setRefreshToken(''); }",
  ].join('\n') : '';

  const clientLines: string[] = [
    '// Drop-in fetch client for ' + state.config.projectName + ' — generated from the SAME IR as the backend.',
    '// Base URL: VITE_API_URL env, else same-origin. Never hardcode production URLs.',
    '',
    "var BASE = '';",
    "try { if (typeof import.meta !== 'undefined' && import.meta.env && import.meta.env.VITE_API_URL) BASE = import.meta.env.VITE_API_URL; } catch (e) {}",
    "try { if (!BASE && typeof process !== 'undefined' && process.env && process.env.API_URL) BASE = process.env.API_URL; } catch (e) {}",
    "if (!BASE) BASE = '" + prefix + "';",
    "var token = '';",
    "var refreshToken = '';",
    "try { token = localStorage.getItem('token') || ''; refreshToken = localStorage.getItem('refresh_token') || ''; } catch (e) {}",
    '',
    'export function setToken(t) { token = t || ' + "''" + '; try { localStorage.setItem(' + "'token'" + ', token); } catch (e) {} }',
    'export function setRefreshToken(t) { refreshToken = t || ' + "''" + '; try { localStorage.setItem(' + "'refresh_token'" + ', refreshToken); } catch (e) {} }',
    'export function getToken() { return token; }',
    'function storeAuth(d) { var data = (d && d.data) || d || {}; if (data.token) setToken(data.token); if (data.refresh_token) setRefreshToken(data.refresh_token); }',
    '',
    'export async function api(path, opts) {',
    '  opts = opts || {};',
    "  var method = opts.method || 'GET';",
    '  var query = opts.query || {};',
    '  var body = opts.body;',
    '  var headers = opts.headers || {};',
    '  var timeoutMs = opts.timeout || 15000;',
    '  var qs = new URLSearchParams(query).toString();',
    '  var h = { ' + "'Content-Type': 'application/json'" + ' };',
    "  if (token) h['Authorization'] = 'Bearer ' + token;",
    '  for (var k in headers) h[k] = headers[k];',
    '  var ctrl = typeof AbortController !== ' + "'undefined'" + ' ? new AbortController() : null;',
    '  var timer = ctrl ? setTimeout(function(){ try { ctrl.abort(); } catch(e){} }, timeoutMs) : null;',
    '  try {',
    '    var res = await fetch(BASE + path + (qs ? ' + "'?'" + ' + qs : ' + "''" + '), {',
    '      method: method, headers: h,',
    '      body: body ? JSON.stringify(body) : undefined,',
    '      signal: ctrl ? ctrl.signal : undefined,',
    '    });',
    '    var data = await res.json().catch(function () { return {}; });',
    "    if (res.status === 401 && refreshToken && path !== '/auth/refresh' && !opts._retried) {",
    "      try { var r = await api('/auth/refresh', { method: 'POST', body: { refresh_token: refreshToken }, _retried: true }); storeAuth(r); h['Authorization'] = 'Bearer ' + token; var res2 = await fetch(BASE + path + (qs ? '?' + qs : ''), { method: method, headers: h, body: body ? JSON.stringify(body) : undefined }); var data2 = await res2.json().catch(function(){ return {}; }); if (!res2.ok) throw Object.assign(new Error(((data2.error||{}).message) || ('HTTP ' + res2.status)), { status: res2.status, code: (data2.error||{}).code, data: data2 }); return data2; } catch (e) { /* refresh failed — fall through */ }",
    '    }',
    "    if (!res.ok) throw Object.assign(new Error(((data.error||{}).message) || ((data.data||{}).error) || ('HTTP ' + res.status)), { status: res.status, code: (data.error||{}).code, data: data });",
    '    return data;',
    '  } catch (e) { if (e && e.name === ' + "'AbortError'" + ') throw Object.assign(new Error(' + "'Request timeout'" + '), { code: ' + "'TIMEOUT'" + ' }); throw e; }',
    '  finally { if (timer) clearTimeout(timer); }',
    '}',
    '',
    clientAuthFns,
    '',
    clientFns,
    '',
  ];
  files.push({ path: 'frontend/api-client.js', language: 'javascript', content: clientLines.join('\n') });

  // Optional Frontend Authentication scaffolding
  if (state.auth.strategy !== 'none' && state.auth.strategy !== 'existing') {
    files.push({
      path: 'frontend/auth/auth-store.js', language: 'javascript',
      content: [
        "import { setToken, setRefreshToken, getToken, api, register as apiRegister, login as apiLogin, refresh as apiRefresh, logout as apiLogout } from '../api-client.js';",
        "",
        "export const authStore = {",
        "  user: null,",
        "  isAuthenticated() { return !!getToken(); },",
        "  getAccessToken() { return getToken(); },",
        "  async getCurrentUser() {",
        "    if (this.user) return this.user;",
        "    return await this.loadUser();",
        "  },",
        "  async loadUser() {",
        "    if (!this.isAuthenticated()) return null;",
        "    try {",
        "      const res = await api('/auth/me');",
        "      this.user = res.data?.user || res.user || null;",
        "      return this.user;",
        "    } catch (e) {",
        "      const refreshed = await this.refresh();",
        "      if (refreshed) {",
        "        try {",
        "          const res2 = await api('/auth/me');",
        "          this.user = res2.data?.user || res2.user || null;",
        "          return this.user;",
        "        } catch (err) {}",
        "      }",
        "      await this.logout();",
        "      return null;",
        "    }",
        "  },",
        "  async login(credentials) {",
        "    const res = await apiLogin(credentials);",
        "    await this.loadUser();",
        "    return res;",
        "  },",
        "  async register(data) {",
        "    const res = await apiRegister(data);",
        "    await this.loadUser();",
        "    return res;",
        "  },",
        "  async refresh() {",
        "    try {",
        "      return await apiRefresh();",
        "    } catch (e) {",
        "      return null;",
        "    }",
        "  },",
        "  async logout() {",
        "    try { await apiLogout(); } catch (e) {}",
        "    setToken('');",
        "    setRefreshToken('');",
        "    this.user = null;",
        "    if (typeof window !== 'undefined' && !window.location.pathname.includes('login.html')) {",
        "      window.location.href = './login.html';",
        "    }",
        "  }",
        "};",
      ].join('\n'),
    });

    files.push({
      path: 'frontend/auth/protected-route.js', language: 'javascript',
      content: [
        "import { authStore } from './auth-store.js';",
        "",
        "export async function requireAuth(roles = []) {",
        "  if (typeof window === 'undefined') return false;",
        "  const currentPath = window.location.pathname + window.location.search;",
        "  if (window.location.pathname.endsWith('login.html') || window.location.pathname.endsWith('register.html')) {",
        "    return true;",
        "  }",
        "  if (!authStore.isAuthenticated()) {",
        "    window.location.href = './login.html?redirect=' + encodeURIComponent(currentPath);",
        "    return false;",
        "  }",
        "  let user = await authStore.getCurrentUser();",
        "  if (!user) {",
        "    const refreshed = await authStore.refresh();",
        "    if (refreshed) user = await authStore.getCurrentUser();",
        "  }",
        "  if (!user) {",
        "    window.location.href = './login.html?redirect=' + encodeURIComponent(currentPath);",
        "    return false;",
        "  }",
        "  if (roles.length > 0 && !roles.includes(user.role)) {",
        "    alert('Access denied: insufficient permissions');",
        "    window.location.href = '../index.html';",
        "    return false;",
        "  }",
        "  return true;",
        "}",
      ].join('\n'),
    });

    files.push({
      path: 'frontend/auth/login.html', language: 'html',
      content: [
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '  <meta charset="UTF-8">',
        '  <title>Login - ' + state.config.projectName + '</title>',
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '  <style>',
        '    body { font-family: sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; background: #f4f6f8; }',
        '    .card { background: white; padding: 2rem; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); width: 100%; max-width: 360px; }',
        '    h2 { margin-top: 0; }',
        '    .form-group { margin-bottom: 1rem; }',
        '    label { display: block; margin-bottom: 0.25rem; font-size: 0.875rem; }',
        '    input { width: 100%; padding: 0.5rem; box-sizing: border-box; border: 1px solid #ccc; border-radius: 4px; }',
        '    button { width: 100%; padding: 0.6rem; background: #0284c7; color: white; border: none; border-radius: 4px; font-weight: bold; cursor: pointer; }',
        '    .error { color: #dc2626; font-size: 0.875rem; margin-bottom: 1rem; display: none; }',
        '  </style>',
        '</head>',
        '<body>',
        '  <div class="card">',
        '    <h2>Sign In</h2>',
        '    <div id="error-msg" class="error"></div>',
        '    <form id="login-form">',
        '      <div class="form-group">',
        '        <label for="email">Email</label>',
        '        <input type="email" id="email" required>',
        '      </div>',
        '      <div class="form-group">',
        '        <label for="password">Password</label>',
        '        <input type="password" id="password" required>',
        '      </div>',
        '      <button type="submit">Sign In</button>',
        '    </form>',
        '  </div>',
        '  <script type="module" src="./login.js"></script>',
        '</body>',
        '</html>',
      ].join('\n'),
    });

    files.push({
      path: 'frontend/auth/login.js', language: 'javascript',
      content: [
        "import { login } from '../api-client.js';",
        "",
        "const form = document.getElementById('login-form');",
        "const errorMsg = document.getElementById('error-msg');",
        "",
        "form.addEventListener('submit', async (e) => {",
        "  e.preventDefault();",
        "  errorMsg.style.display = 'none';",
        "  const email = document.getElementById('email').value;",
        "  const password = document.getElementById('password').value;",
        "  try {",
        "    await login({ email, password });",
        "    const params = new URLSearchParams(window.location.search);",
        "    window.location.href = params.get('redirect') || '/';",
        "  } catch (err) {",
        "    errorMsg.textContent = err.message || 'Login failed';",
        "    errorMsg.style.display = 'block';",
        "  }",
        "});",
      ].join('\n'),
    });

    files.push({
      path: 'frontend/auth/register.html', language: 'html',
      content: [
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '  <meta charset="UTF-8">',
        '  <title>Register - ' + state.config.projectName + '</title>',
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '  <style>',
        '    body { font-family: sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; background: #f4f6f8; }',
        '    .card { background: white; padding: 2rem; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); width: 100%; max-width: 360px; }',
        '    h2 { margin-top: 0; }',
        '    .form-group { margin-bottom: 1rem; }',
        '    label { display: block; margin-bottom: 0.25rem; font-size: 0.875rem; }',
        '    input { width: 100%; padding: 0.5rem; box-sizing: border-box; border: 1px solid #ccc; border-radius: 4px; }',
        '    button { width: 100%; padding: 0.6rem; background: #16a34a; color: white; border: none; border-radius: 4px; font-weight: bold; cursor: pointer; }',
        '    .error { color: #dc2626; font-size: 0.875rem; margin-bottom: 1rem; display: none; }',
        '  </style>',
        '</head>',
        '<body>',
        '  <div class="card">',
        '    <h2>Create Account</h2>',
        '    <div id="error-msg" class="error"></div>',
        '    <form id="register-form">',
        '      <div class="form-group">',
        '        <label for="name">Full Name</label>',
        '        <input type="text" id="name" required>',
        '      </div>',
        '      <div class="form-group">',
        '        <label for="email">Email</label>',
        '        <input type="email" id="email" required>',
        '      </div>',
        '      <div class="form-group">',
        '        <label for="password">Password (8+ chars)</label>',
        '        <input type="password" id="password" minlength="8" required>',
        '      </div>',
        '      <button type="submit">Register</button>',
        '    </form>',
        '  </div>',
        '  <script type="module" src="./register.js"></script>',
        '</body>',
        '</html>',
      ].join('\n'),
    });

    files.push({
      path: 'frontend/auth/register.js', language: 'javascript',
      content: [
        "import { register } from '../api-client.js';",
        "",
        "const form = document.getElementById('register-form');",
        "const errorMsg = document.getElementById('error-msg');",
        "",
        "form.addEventListener('submit', async (e) => {",
        "  e.preventDefault();",
        "  errorMsg.style.display = 'none';",
        "  const name = document.getElementById('name').value;",
        "  const email = document.getElementById('email').value;",
        "  const password = document.getElementById('password').value;",
        "  try {",
        "    await register({ name, email, password });",
        "    window.location.href = '/';",
        "  } catch (err) {",
        "    errorMsg.textContent = err.message || 'Registration failed';",
        "    errorMsg.style.display = 'block';",
        "  }",
        "});",
      ].join('\n'),
    });
  }

  // OpenAPI 3.x generated from the SAME canonical types (IR) — schemas per resource
  const openApiSchemas: Record<string, unknown> = {};
  for (const t of sortedTables) {
    const props: Record<string, unknown> = {};
    const required: string[] = [];
    for (const c of t.columns) {
      if (['password'].includes(c.name)) continue; // never expose password in schemas
      const oa = openApiTypeFor(c.name, c.type);
      props[c.name] = { ...oa, nullable: c.nullable };
      if (!c.nullable && !c.isAutoIncrement && !['created_at', 'updated_at', 'deleted_at', 'id'].includes(c.name)) required.push(c.name);
    }
    openApiSchemas[toClassName(t.name)] = { type: 'object', properties: props, required };
  }
  const paths: Record<string, unknown> = {};
  const addOp = (method: string, key: string, summary: string, auth: string, schemaRef?: string) => {
    const existing = (paths[key] as Record<string, unknown>) || {};
    existing[method] = {
      summary,
      security: auth === 'none' ? [] : [{ bearerAuth: [] }],
      ...(schemaRef ? { requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/' + schemaRef } } } } } : {}),
      responses: {
        '200': { description: 'OK', content: { 'application/json': { schema: { type: 'object' } } } },
        '201': { description: 'Created' },
        '401': { description: 'Unauthorized' },
        '403': { description: 'Forbidden' },
        '404': { description: 'Not found' },
        '405': { description: 'Method not allowed' },
        '422': { description: 'Validation error' },
        '429': { description: 'Rate limited' },
      },
    };
    paths[key] = existing;
  };
  if (state.auth.strategy !== 'none' && state.auth.strategy !== 'existing') {
    addOp('post', prefix + '/auth/register', 'Register', 'none', 'User');
    addOp('post', prefix + '/auth/login', 'Login', 'none');
    addOp('post', prefix + '/auth/logout', 'Logout', 'required');
    addOp('post', prefix + '/auth/refresh', 'Refresh token', 'none');
    addOp('get', prefix + '/auth/me', 'Current user', 'required');
  }
  for (const e of state.endpoints) {
    const key = e.path.startsWith(prefix) ? e.path : (prefix + (e.path.startsWith('/') ? '' : '/') + e.path);
    addOp(e.method.toLowerCase(), key, e.description, e.auth, e.table ? toClassName(e.table) : undefined);
  }
  // Ensure PATCH + health are documented even if endpoints list omits them
  for (const t of sortedTables) {
    addOp('patch', prefix + '/' + t.name + '/{id}', 'Patch ' + t.name, 'required', toClassName(t.name));
  }
  addOp('get', prefix + '/health', 'Health', 'none');
  addOp('get', prefix + '/health/live', 'Liveness', 'none');
  addOp('get', prefix + '/health/ready', 'Readiness', 'none');

  files.push({
    path: 'docs/openapi.json', language: 'json',
    content: JSON.stringify({
      openapi: '3.0.3',
      info: { title: state.config.projectName, version: '1.0.0', description: 'Generated from canonical IR v' + IR_VERSION + ' by generator v' + GENERATOR_VERSION },
      servers: [{ url: 'http://localhost:8000' }],
      paths,
      components: {
        securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
        schemas: openApiSchemas,
      },
    }, null, 2),
  });

  const readmeLines: string[] = [
    '# ' + state.config.projectName,
    '',
    'Generated with **PHP Backend Builder** v' + GENERATOR_VERSION + ' (IR v' + IR_VERSION + ') — PHP 8.2 + PDO + MySQL.',
    '',
    '## Quick start',
    '',
    '```bash',
    'composer install',
    'cp .env.example .env',
    'php bin/backend key:generate   # crypto-secure JWT_SECRET -> .env (never committed)',
    'php bin/backend doctor         # PHP/ext/env/DB/JWT/migration checks',
    'mysql -u root -p -e "CREATE DATABASE ' + state.config.dbName + ' CHARACTER SET utf8mb4;"',
    'php database/migrate.php migrate   # tracked via migrations table',
    'php database/migrate.php migrate:status',
    'php bin/backend serve            # or: php -S localhost:8000 -t backend/public',
    '```',
    '',
    '## Auth',
    '',
    '```bash',
    "curl -X POST http://localhost:8000" + prefix + "/auth/register -H 'Content-Type: application/json' -d '{\"name\":\"Ada\",\"email\":\"ada@example.com\",\"password\":\"secret123\"}'",
    'curl http://localhost:8000' + prefix + '/health/live',
    'curl http://localhost:8000' + prefix + '/health/ready',
    '```',
    'Routes: POST /auth/register, POST /auth/login, POST /auth/logout, POST /auth/refresh, GET /auth/me.',
    'Refresh tokens rotate on every use; only SHA-256 hashes are stored; reuse is rejected.',
    '',
    '## Layout',
    '',
    '- backend/public/index.php — front controller (RequestId, Handler, security headers, CORS, rate limit, auth guard, 404/405)',
    '- backend/controllers/ — thin CRUD (validation rules from IR, PATCH=partial, password logic ONLY in users/Auth)',
    '- backend/models/ — fillable/hidden/casts from canonical IR (password always hidden)',
    '- backend/support/ — Container (PSR-11), Request, Response (envelope), Router (404/405), Middleware, RateLimiterInterface, Logger (redacted), Handler, Jwt, RequestId',
    '- database/ — schema.sql + ordered migrations + migrate.php (migrate|rollback|status|fresh)',
    '- bin/backend — doctor|key:generate|routes|serve',
    '- frontend/api-client.js — IR-generated client (timeout, refresh, request-id, no hardcoded URL)',
    '- docs/openapi.json — generated from SAME IR (schemas per resource)',
    '- tests/ApiTest.php — health/auth/CRUD/validation/pagination (phpunit)',
    '- composer.json / phpunit.xml — PSR-4, PHPUnit, PHPStan',
    '',
    '## Deployment',
    '',
    '- Web root MUST be `backend/public/` (Apache/Nginx/PHP-FPM).',
    '- `docker-compose up --build` for optional Docker (not required locally).',
    '- Production: APP_ENV=production, APP_DEBUG=false, CORS_ORIGINS=https://your-frontend, HTTPS + HSTS.',
    '',
    '## Security notes',
    '',
    '- All SQL uses bound parameters; sort/filter columns allow-listed; max page size enforced.',
    '- Passwords: password_hash/password_verify, never serialized, never logged.',
    '- JWT: minimal claims (sub/jti/iat/exp), hash_equals verify, empty default + key:generate.',
    '- Rate limiting with file locking (auth stricter, 429 + Retry-After); CORS never wildcard+credentials.',
    '- Errors: standardized {success,error{code,message,details},request_id}; prod hides SQL/paths/traces.',
    '',
  ];
  files.push({ path: 'README.md', language: 'markdown', content: readmeLines.join('\n') });

  // Production deployment files — never emit secrets, only .env.example
  files.push({
    path: 'Dockerfile', language: 'docker',
    content: [
      'FROM php:8.2-cli',
      'WORKDIR /app',
      'COPY backend/ backend/',
      'COPY database/ database/',
      'COPY .env.example .env.example',
      'RUN docker-php-ext-install pdo pdo_mysql',
      'EXPOSE 8000',
      'CMD ["php", "-S", "0.0.0.0:8000", "-t", "backend/public"]',
    ].join('\n') + '\n',
  });
  files.push({
    path: 'docker-compose.yml', language: 'yaml',
    content: [
      'version: "3.8"',
      'services:',
      '  app:',
      '    build: .',
      '    ports: ["8000:8000"]',
      `    environment: [DB_HOST=db, DB_NAME=${state.config.dbName}, DB_USER=root, DB_PASS=secret, JWT_SECRET=\${JWT_SECRET}]`,
      '    depends_on: [db]',
      '  db:',
      '    image: mysql:8',
      `    environment: [MYSQL_DATABASE=${state.config.dbName}, MYSQL_ROOT_PASSWORD=secret]`,
      '    ports: ["3306:3306"]',
      '    volumes: [db_data:/var/lib/mysql]',
      'volumes: { db_data: {} }',
    ].join('\n') + '\n',
  });

  // Composer: PSR-4 autoload + PHPUnit + PHPStan (minimal, genuine deps only)
  files.push({
    path: 'composer.json', language: 'json',
    content: JSON.stringify({
      name: state.config.projectName.toLowerCase().replace(/[^a-z0-9_-]/g, '-'),
      description: 'Generated API — PHP 8.2 + PDO',
      require: { php: '>=8.2' },
      'require-dev': { 'phpunit/phpunit': '^10.0', 'phpstan/phpstan': '^1.0' },
      autoload: { 'psr-4': { 'App\\': 'backend/' } },
      scripts: { test: 'phpunit tests', analyse: 'phpstan analyse backend --level=5' },
    }, null, 2) + '\n',
  });
  files.push({
    path: 'phpunit.xml', language: 'xml',
    content: '<?xml version="1.0"?>\n<phpunit bootstrap="tests/bootstrap.php" colors="true">\n  <testsuites><testsuite name="api"><directory>tests</directory></testsuite></testsuites>\n</phpunit>\n',
  });

  // CLI: backend new/generate/validate/migrate/routes/openapi/doctor/key:generate/serve
  files.push({
    path: 'bin/backend', language: 'php',
    content: '#!/usr/bin/env php\n<?php\n' + header('CLI: backend doctor|key:generate|routes|openapi|migrate|serve').replace('<?php\n', '') +
      "$cmd = $argv[1] ?? 'help';\n" +
      "if ($cmd === 'doctor') { $cfg = file_exists(__DIR__ . '/../.env') ? parse_ini_file(__DIR__ . '/../.env') : []; $ok = true; echo (PHP_VERSION_ID >= 80200 ? 'OK' : 'FAIL') . ' php ' . PHP_VERSION . PHP_EOL; foreach (['pdo','pdo_mysql','json','mbstring'] as $e) { $has = extension_loaded($e); echo ($has ? 'OK' : 'MISSING') . ' ext-' . $e . PHP_EOL; if (!$has) $ok = false; } echo ((($cfg['JWT_SECRET'] ?? getenv('JWT_SECRET')) ?: '') !== '' ? 'OK' : 'FAIL') . ' jwt-secret (run key:generate)' . PHP_EOL; echo ($ok ? 'doctor: PASS' : 'doctor: FAIL') . PHP_EOL; exit($ok ? 0 : 1); }\n" +
      "if ($cmd === 'key:generate') { $key = bin2hex(random_bytes(32)); $env = __DIR__ . '/../.env'; $base = is_file($env) ? file_get_contents($env) : file_get_contents(__DIR__ . '/../.env.example'); if (strpos($base, 'JWT_SECRET=') !== false) { $base = preg_replace('/^JWT_SECRET=.*$/m', 'JWT_SECRET=' . $key, $base); } else { $base .= PHP_EOL . 'JWT_SECRET=' . $key . PHP_EOL; } file_put_contents($env, $base); echo 'JWT_SECRET generated -> .env' . PHP_EOL; exit(0); }\n" +
      "if ($cmd === 'routes') { $cfg = require __DIR__ . '/../backend/config/app.php'; require __DIR__ . '/../backend/public/index.php'; exit(0); }\n" +
      "if ($cmd === 'serve') { $port = $argv[2] ?? '8000'; echo 'Serving on http://localhost:' . $port . PHP_EOL; passthru('php -S localhost:' . escapeshellarg($port) . ' -t backend/public'); exit(0); }\n" +
      "echo 'backend doctor|key:generate|routes|openapi|migrate|serve' . PHP_EOL;\n",
  });

  // Generated PHPUnit suite: health/auth/CRUD/validation/pagination/security
  files.push({
    path: 'tests/bootstrap.php', language: 'php',
    content: header('PHPUnit bootstrap') + "$_SERVER['APP_ENV'] = 'testing';\nrequire __DIR__ . '/../backend/config/database.php';\n",
  });
  files.push({
    path: 'tests/ApiTest.php', language: 'php',
    content: header('Generated API tests — health, auth, CRUD, validation, pagination') +
      "use PHPUnit\\Framework\\TestCase;\nfinal class ApiTest extends TestCase\n{\n    public function testHealthRouteRegistered(): void { $this->assertFileExists(__DIR__ . '/../backend/public/index.php'); $src = file_get_contents(__DIR__ . '/../backend/public/index.php'); $this->assertStringContainsString('/health', $src); }\n" +
      (state.auth.strategy !== 'none' && state.auth.strategy !== 'existing' ? "    public function testAuthRoutesRegistered(): void { $src = file_get_contents(__DIR__ . '/../backend/public/index.php'); foreach (['/auth/register','/auth/login','/auth/logout','/auth/refresh','/auth/me'] as $r) { $this->assertStringContainsString($r, $src, 'missing ' . $r); } }\n" : '') +
      "    public function testNoHardcodedJwtSecret(): void { $cfg = file_get_contents(__DIR__ . '/../backend/config/app.php'); $this->assertStringNotContainsString('change-me-in-production', $cfg); $env = file_get_contents(__DIR__ . '/../.env.example'); $this->assertMatchesRegularExpression('/^JWT_SECRET=$/m', $env); }\n" +
      "    public function testPasswordNeverSerialized(): void { $src = file_get_contents(__DIR__ . '/../backend/support/Model.php'); $this->assertStringContainsString('unset(' . chr(36) . 'row', $src); }\n" +
      "    public function testMigrationsOrdered(): void { $files = glob(__DIR__ . '/../database/migrations/*.php'); sort($files); $this->assertNotEmpty($files); $this->assertMatchesRegularExpression('/^\\\\d{3}_/', basename($files[0])); }\n" +
      "    public function testOpenApiMatchesRoutes(): void { $oa = json_decode(file_get_contents(__DIR__ . '/../docs/openapi.json'), true); $this->assertEquals('3.0.3', substr($oa['openapi'],0,5)); $this->assertNotEmpty($oa['paths']); }\n}\n",
  });

  return files;
}

export function downloadFile(path: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const parts = path.split('/');
  a.download = parts[parts.length - 1] || 'file.txt';
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
