/**
 * Exporter: bundles the complete working project (backend + database +
 * integrated frontend + docs) into a downloadable ZIP (browser-side).
 */
import JSZip from 'jszip';
import type { GenFile } from '@/lib/builder';
import type { FileChange, ProjectFile } from '@/shared/types';
import { applyApprovedChanges } from '@/integration/planner';

export interface ExportInput {
  projectName: string;
  backend: GenFile[];
  frontendOriginal: ProjectFile[];
  frontendChanges: FileChange[];
  notes: string[];
  /** Mandatory gate: caller must pass validation result; export throws when blocked. */
  validation?: { blocking: boolean; issues: Array<{ code: string; message: string }> };
}

/** Normalize + guard paths against ../, absolute paths, unsafe names (Rule §29). */
export function safeExportPath(raw: string): string {
  let p = raw.replace(/\\/g, '/').trim();
  if (p.startsWith('/')) throw new Error(`Unsafe absolute path: ${raw}`);
  const parts = p.split('/').filter(Boolean);
  const clean: string[] = [];
  for (const part of parts) {
    if (part === '..' || part === '.') throw new Error(`Unsafe path traversal: ${raw}`);
    if (!/^[A-Za-z0-9._-]+$/.test(part) && !/^[A-Za-z0-9._-]+\.[A-Za-z0-9]+$/.test(part)) {
      if (!/^[A-Za-z0-9._-]+$/.test(part)) throw new Error(`Unsafe filename: ${raw}`);
    }
    clean.push(part);
  }
  if (clean.length === 0) throw new Error(`Empty path: ${raw}`);
  return clean.join('/');
}

export async function buildExportZip(input: ExportInput): Promise<Blob> {
  // BLOCKING RULE (§25): critical failure = export blocked, no silent override.
  if (input.validation?.blocking) {
    const reasons = input.validation.issues.filter((i) => i).map((i) => `${i.code}: ${i.message}`).slice(0, 5).join('; ');
    throw new Error(`EXPORT BLOCKED — critical validation failed: ${reasons || 'see Validation Center'}`);
  }
  const zip = new JSZip();
  const root = zip.folder(input.projectName.replace(/[^a-zA-Z0-9_-]/g, '_') || 'fullstack-app');
  if (!root) throw new Error('zip init failed');

  for (const f of input.backend) {
    // Never export secrets: skip real .env, only .env.example (empty placeholders)
    if (/(^|\/)\.env$/.test(f.path)) continue;
    root.file(safeExportPath(f.path), f.content);
  }

  const integrated = applyApprovedChanges(input.frontendOriginal, input.frontendChanges);
  for (const f of integrated) {
    if (f.isBinary) continue;
    // keep frontend under frontend-original/ + frontend-integrated/ for clarity
    root.file(`frontend-original/${f.relativePath}`, f.content);
  }
  for (const f of integrated) {
    if (f.isBinary) continue;
    root.file(`frontend/${f.relativePath}`, f.content);
  }

  root.file('PROJECT-NOTES.md', [
    `# ${input.projectName} — complete full-stack export`,
    '',
    'Generated by PHP Backend Builder (FRONTEND → ANALYZE → … → EXPORT).',
    '',
    '## Layout',
    '',
    '- `backend/` — zero-dependency PHP 8.2 + PDO API',
    '- `database/` — schema.sql + migrations + migrate.php',
    '- `frontend/` — your ORIGINAL frontend with approved integration changes applied',
    '- `frontend-original/` — untouched copy for diffing',
    '- `docs/` — openapi.json',
    '- `frontend/api-client.js` (backend bundle) — drop-in fetch client',
    '',
    '## Run',
    '',
    '```bash',
    'mysql -u root -p -e "CREATE DATABASE app CHARACTER SET utf8mb4;"',
    'mysql -u root -p app < database/schema.sql',
    'cp .env.example .env',
    'php -S localhost:8000 -t backend/public',
    '```',
    '',
    '## Integration decisions',
    '',
    ...input.notes.map((n) => `- ${n}`),
    '',
  ].join('\n'));

  return root.generateAsync({ type: 'blob', compression: 'DEFLATE' });
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}
