/**
 * Integration planner: computes minimal, reviewable changes to the ORIGINAL
 * frontend so it talks to the generated PHP backend.
 * Produces FileChange[] with unified diffs — nothing is applied silently.
 */
import type { AnalysisResult, BackendRequirements, FileChange, ProjectFile } from '@/shared/types';

let seq = 0;
function nid(prefix: string): string {
  seq += 1;
  return `${prefix}_${seq.toString(36)}_${Date.now().toString(36).slice(-4)}`;
}

export interface IntegrationPlan {
  changes: FileChange[];
  summary: string[];
}

const API_CLIENT_FILENAME = 'src/lib/api-client.js';

function apiClientContent(basePath: string): string {
  return [
    '// Generated by PHP Backend Builder — drop-in API client.',
    `// Base URL is configurable via VITE_API_URL (defaults to the PHP dev server).`,
    `var BASE = 'http://localhost:8000${basePath}';`,
    "try { if (typeof import.meta !== 'undefined' && import.meta.env && import.meta.env.VITE_API_URL) BASE = import.meta.env.VITE_API_URL; } catch (e) {}",
    "var token = '';",
    "try { token = localStorage.getItem('token') || ''; } catch (e) {}",
    '',
    'export function setToken(t) { token = t || \'\'; try { localStorage.setItem(\'token\', token); } catch (e) {} }',
    'export function getToken() { return token; }',
    '',
    'export async function api(path, opts) {',
    '  opts = opts || {};',
    "  var qs = new URLSearchParams(opts.query || {}).toString();",
    '  var h = { \'Content-Type\': \'application/json\' };',
    "  if (token) h['Authorization'] = 'Bearer ' + token;",
    '  var res = await fetch(BASE + path + (qs ? \'?\' + qs : \'\'), {',
    '  method: opts.method || \'GET\', headers: h,',
    '    body: opts.body ? JSON.stringify(opts.body) : undefined });',
    '  var data = await res.json().catch(function () { return {}; });',
    "  if (!res.ok) throw Object.assign(new Error(data.error || ('HTTP ' + res.status)), { status: res.status, data: data });",
    '  return data;',
    '}',
    "export async function login(d) { var r = await api('/auth/login', { method: 'POST', body: d }); if (r.token) setToken(r.token); return r; }",
    "export async function register(d) { var r = await api('/auth/register', { method: 'POST', body: d }); if (r.token) setToken(r.token); return r; }",
    '',
  ].join('\n');
}

function toDiff(oldText: string, newText: string, filePath: string): FileChange['diff'] {
  const oldLines = oldText.split('\n');
  const newLines = newText.split('\n');
  // naive prefix/suffix diff -> single hunk (good enough for review UI)
  let prefix = 0;
  while (prefix < oldLines.length && prefix < newLines.length && oldLines[prefix] === newLines[prefix]) prefix += 1;
  let suffix = 0;
  while (
    suffix < oldLines.length - prefix &&
    suffix < newLines.length - prefix &&
    oldLines[oldLines.length - 1 - suffix] === newLines[newLines.length - 1 - suffix]
  ) suffix += 1;
  const removed = oldLines.slice(prefix, oldLines.length - suffix);
  const added = newLines.slice(prefix, newLines.length - suffix);
  const ctxBefore = oldLines.slice(Math.max(0, prefix - 2), prefix);
  const ctxAfter = oldLines.slice(oldLines.length - suffix, oldLines.length - suffix + 2);
  const lines: FileChange['diff'] extends undefined ? never : NonNullable<FileChange['diff']>[number]['lines'] = [
    ...ctxBefore.map((content) => ({ type: 'context' as const, content })),
    ...removed.map((content) => ({ type: 'remove' as const, content })),
    ...added.map((content) => ({ type: 'add' as const, content })),
    ...ctxAfter.map((content) => ({ type: 'context' as const, content })),
  ];
  void filePath;
  return [{ oldStart: Math.max(1, prefix - 1), oldLines: removed.length + 2, newStart: Math.max(1, prefix - 1), newLines: added.length + 2, lines }];
}

export function planIntegration(
  frontendFiles: ProjectFile[],
  analysis: AnalysisResult,
  requirements: BackendRequirements
): IntegrationPlan {
  const changes: FileChange[] = [];
  const summary: string[] = [];
  const basePath = requirements.api.basePath || '/api/v1';

  // 1. Add api-client (new file — never overwrites user code)
  const alreadyHasClient = frontendFiles.some((f) =>
    /api-client|apiClient|api\.js|client\.js/i.test(f.relativePath) && /BASE.*localhost:8000/.test(f.content)
  );
  if (!alreadyHasClient) {
    changes.push({
      id: nid('chg'),
      filePath: API_CLIENT_FILENAME,
      changeType: 'add',
      newContent: apiClientContent(basePath),
      description: 'Add generated fetch client (new file, no existing code touched). Configure via VITE_API_URL.',
      requirementIds: requirements.api.endpoints.map((e) => e.id).slice(0, 5),
      approved: false,
      applied: false,
    });
    summary.push('Add src/lib/api-client.js (new file)');
  }

  // 2. Add .env.example entry for VITE_API_URL
  const envFile = frontendFiles.find((f) => /(^|\/)\.env(\.|$)/i.test(f.relativePath) || f.relativePath.endsWith('.env.example'));
  const envLine = `VITE_API_URL=http://localhost:8000${basePath}`;
  if (envFile) {
    if (!envFile.content.includes('VITE_API_URL')) {
      const next = envFile.content.replace(/\s+$/, '') + `\n${envLine}\n`;
      changes.push({
        id: nid('chg'),
        filePath: envFile.relativePath,
        changeType: 'modify',
        originalContent: envFile.content,
        newContent: next,
        diff: toDiff(envFile.content, next, envFile.relativePath),
        description: 'Append VITE_API_URL so the frontend can target the PHP dev server.',
        requirementIds: [],
        approved: false,
        applied: false,
      });
      summary.push(`Append VITE_API_URL to ${envFile.relativePath}`);
    }
  } else {
    changes.push({
      id: nid('chg'),
      filePath: '.env.example',
      changeType: 'add',
      newContent: `${envLine}\n`,
      description: 'Add .env.example with the API base URL.',
      requirementIds: [],
      approved: false,
      applied: false,
    });
    summary.push('Add .env.example with VITE_API_URL');
  }

  // 3. Propose fetch replacements for mock/local-only data (as reviewable diffs, max 5)
  const mockDriven = analysis.mockData.filter((m) => m.classification === 'database_data').slice(0, 5);
  for (const m of mockDriven) {
    const host = frontendFiles.find((f) => f.relativePath === m.path);
    if (!host) continue;
    const entity = m.entityCandidate ?? 'records';
    const anchor = `import { api } from '../lib/api-client'; // PHP Backend Builder: replace mock "${m.variableName}" with live API`;
    if (host.content.includes('../lib/api-client')) continue;
    const lines = host.content.split('\n');
    // insert import after last import line
    let insertAt = 0;
    for (let i = 0; i < lines.length; i++) {
      if (/^\s*import\b/.test(lines[i])) insertAt = i + 1;
      else if (i > 12) break;
    }
    const next = [...lines.slice(0, insertAt), anchor, `// Example: const data = await api('/${entity}');`, ...lines.slice(insertAt)].join('\n');
    changes.push({
      id: nid('chg'),
      filePath: host.relativePath,
      changeType: 'modify',
      originalContent: host.content,
      newContent: next,
      diff: toDiff(host.content, next, host.relativePath),
      description: `Wire "${m.variableName}" to GET ${basePath}/${entity} (comment + import only — data mapping left to developer).`,
      requirementIds: [],
      approved: false,
      applied: false,
    });
    summary.push(`Propose live-API wiring in ${host.relativePath}`);
  }

  if (changes.length === 0) {
    summary.push('No integration changes needed — frontend already targets the API.');
  }

  return { changes, summary };
}

/** Apply approved changes to an in-memory file list (export/preview). */
export function applyApprovedChanges(files: ProjectFile[], changes: FileChange[]): ProjectFile[] {
  const next = files.map((f) => ({ ...f }));
  for (const c of changes) {
    if (!c.approved) continue;
    if (c.changeType === 'add') {
      if (!next.some((f) => f.relativePath === c.filePath)) {
        next.push({
          path: c.filePath,
          relativePath: c.filePath,
          content: c.newContent ?? '',
          size: (c.newContent ?? '').length,
          extension: c.filePath.split('.').pop() ?? '',
          isBinary: false,
        });
      }
    } else if (c.changeType === 'modify' && c.newContent !== undefined) {
      const idx = next.findIndex((f) => f.relativePath === c.filePath);
      if (idx >= 0) next[idx] = { ...next[idx], content: c.newContent, size: c.newContent.length };
    }
  }
  return next;
}
